// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWS.java.vsl in andromda-webservices. Do not modify by hand!.
//
package bw.co.roguesystems.rfiles.document;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

/**
 * 
 * TODO: Model Documentation for bw.co.roguesystems.fsrfp.document.DocumentApi
 */
@RequestMapping("/document")
@Tag(name = "Document Attachments", description = "Managing document attached to different targets.")
public interface DocumentApi {

    @GetMapping("/download/{id}")
    public ResponseEntity<?> downloadFile(@PathVariable(name = "id", required = true) String id);

    @GetMapping("/documentTypeId/{documentTypeId}")
    public ResponseEntity<?> findByDocumentType(@PathVariable(name = "documentTypeId", required = true) String documentTypeId);

    @GetMapping("/{id}")
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<?> findById(@PathVariable(name = "id", required = true) String id);

    @GetMapping("/target/{target}/{targetId}")
    @Operation(summary = "Find Document by Target", description = "Get the document with the given target and targetId")
    public ResponseEntity<?> findByTarget(@PathVariable(name = "target", required = true) String target, @PathVariable(name = "targetId", required = true) String targetId);

    @GetMapping()
    public ResponseEntity<?> getAll();

    @GetMapping("/paged")
    public ResponseEntity<?> getAllPaged(@RequestParam(name = "pageNumber", required = false) Integer pageNumber, @RequestParam(name = "pageSize", required = false) Integer pageSize);

    @DeleteMapping("/{id}")
    public ResponseEntity<?> remove(@PathVariable(name = "id", required = true) String id);

    @PostMapping()
    public ResponseEntity<?> save(@RequestBody(required = true) DocumentDTO document);

    @GetMapping("/search")
    public ResponseEntity<?> search(@RequestParam(name = "criteria", required = false) String criteria);

    @PutMapping("/update/{id}")
    public ResponseEntity<?> updateFile(@PathVariable(name = "id", required = true) String id, @RequestParam(name = "file", required = true) MultipartFile file);

    @PostMapping("/upload/{target}/{targetId}/type/{documentTypeId}")
    public ResponseEntity<?> upload(@PathVariable(name = "target", required = true) String target, @PathVariable(name = "targetId", required = true) String targetId, @PathVariable(name = "documentTypeId", required = true) String documentTypeId, @RequestBody(required = true) MultipartFile file);
}