// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.roguesystems.rfiles.document;

import bw.co.roguesystems.rfiles.AuditTracker;
import bw.co.roguesystems.rfiles.Auditable;
import bw.co.roguesystems.rfiles.AuditableDTO;
import bw.co.roguesystems.rfiles.minio.MinioService;
import io.swagger.v3.oas.annotations.tags.Tag;

import java.io.File;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.client.RestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.core.io.FileSystemResource;

@RestController
public class DocumentApiImpl extends DocumentApiBase {

    @Value("${minio.bucket-name}")
    private String licensingBucket;

    private String solrProcessorUrl;

    private final RestTemplate restTemplate;
    private final MinioService minioService;

    public DocumentApiImpl(DocumentService documentService, MinioService minioService) {

        super(documentService);

        this.restTemplate = new RestTemplate();
        this.minioService = minioService;
    }


    @Override
    public ResponseEntity<?> handleDownloadFile(String id) {

        try {
            DocumentDTO document = documentService.findById(id);
            if (document == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Document not found");
            }

            String fileUrl = document.getUrl();
            if (fileUrl == null || fileUrl.isEmpty()) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body("File URL not found");
            }

            InputStream fileStream = minioService.downloadFile(fileUrl);
            if (fileStream == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND).body("File not found in MinIO");
            }

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_OCTET_STREAM);
            headers.setContentDispositionFormData("attachment", document.getFilename());

            return ResponseEntity.ok()
                    .headers(headers)
                    .body(new InputStreamResource(fileStream));

        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }

    }

    @Override
    public ResponseEntity<?> handleFindByDocumentType(String documentTypeId) {
        try {
            Optional<?> data = Optional.of(documentService.findByDocumentType(documentTypeId));
            ResponseEntity<?> response;

            if(data.isPresent()) {
                response = ResponseEntity.status(HttpStatus.OK).body(data.get());
            } else {
                response = ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    @Override
    public ResponseEntity<?> handleFindById(String id) {
        try {
            Optional<?> data = Optional.of(documentService.findById(id));
            ResponseEntity<?> response;

            if(data.isPresent()) {
                response = ResponseEntity.status(HttpStatus.OK).body(data.get());
            } else {
                response = ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    @Override
    public ResponseEntity<?> handleFindByTarget(String target, String targetId) {
        try {
            Optional<?> data = Optional.of(documentService.findByTarget(target, targetId));
            ResponseEntity<?> response;

            if(data.isPresent()) {
                response = ResponseEntity.status(HttpStatus.OK).body(data.get());
            } else {
                response = ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    @Override
    public ResponseEntity<?> handleGetAll() {
        try {
            Optional<?> data = Optional.of(documentService.getAll());
            ResponseEntity<?> response;

            if(data.isPresent()) {
                response = ResponseEntity.status(HttpStatus.OK).body(data.get());
            } else {
                response = ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    @Override
    public ResponseEntity<?> handleGetAllPaged(Integer pageNumber, Integer pageSize) {
        try {
            Optional<?> data = Optional.of(documentService.getAll(pageNumber, pageSize));
            ResponseEntity<?> response;

            if(data.isPresent()) {
                response = ResponseEntity.status(HttpStatus.OK).body(data.get());
            } else {
                response = ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    @Override
    public ResponseEntity<?> handleRemove(String id) {
        try {
            Optional<?> data = Optional.of(documentService.remove(id));
            ResponseEntity<?> response;

            if(data.isPresent()) {
                response = ResponseEntity.status(HttpStatus.OK).body(data.get());
            } else {
                response = ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    @Override
    public ResponseEntity<?> handleSave(DocumentDTO document) {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(document, authentication);
            Optional<?> data = Optional.of(documentService.save(document));
            ResponseEntity<?> response;

            if(data.isPresent()) {
                response = ResponseEntity.status(HttpStatus.OK).body(data.get());
            } else {
                response = ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    @Override
    public ResponseEntity<?> handleSearch(String criteria) {
        try {
            Optional<?> data = Optional.of(documentService.search(criteria));
            ResponseEntity<?> response;

            if(data.isPresent()) {
                response = ResponseEntity.status(HttpStatus.OK).body(data.get());
            } else {
                response = ResponseEntity.status(HttpStatus.NOT_FOUND).build();
            }

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    @Override
    public ResponseEntity<?> handleUpdateFile(String id, MultipartFile file) {
        try {

            DocumentDTO document = documentService.findById(id);
            StringBuilder fileDir = new StringBuilder();

            String targetId = document.getOwnerId();

            // switch (document.getTarget()) {
            //     case PROCESS:
            //         // AnnualReturnDTO annualReturn = annualReturnService.findById(targetId);
            //         // fileDir.append(annualReturn.getLicenceConfigCode())
            //         //         .append("/return/")
            //         //         .append(LocalDate.now().getYear())
            //         //         .append("/");
            //         break;

            //     case REGULATOR:
            //         // LicenceApplicationDTO application = licenceApplicationService.findById(targetId);
            //         // if (application != null) {
            //         //     fileDir.append(application.getLicenceConfig().getCode())
            //         //             .append("/application")
            //         //             .append("/").append(application.getApplicationNumber())
            //         //             .append("/");
            //         // }
            //         break;
            //     case SERVICE:
            //     //     LicenceRenewalDTO renewal = licenceRenewalService.findById(targetId);
            //     //     fileDir.append(renewal.getLicence().getLicenceConfigCode())
            //     //             .append("/renewal/")
            //     //             .append(renewal.getLicence().getLicenceNumber())
            //     //             .append("/")
            //     //             .append(LocalDate.now().getYear())
            //     //             .append("/");

            //         break;
            //     default:
            //         throw new IllegalArgumentException("Unsupported target type: " + document.getTarget());

            // }

            fileDir.append(file.getOriginalFilename());
            // UploadResponse uploadResponse = storageClient.uploadFile(file, fileDir.toString(), licensingBucket, true);

            // document.setUrl(uploadResponse.getFileDownloadUri());
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(document, authentication);

            Optional<?> data = Optional.of(documentService.save(document)); // TODO: Add custom code here;
            ResponseEntity<?> response;

            response = ResponseEntity.status(HttpStatus.OK).body(data.get());

            return response;
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    private String uploadToMinio(MultipartFile file, String fileName) throws Exception {
        // Upload the file to MinIO
        try (InputStream inputStream = file.getInputStream()) {

            String url = minioService.uploadFile(fileName, inputStream, file.getSize(), file.getContentType());
            System.out.println("File uploaded to MinIO: " + url);
            return url;

        } catch(Exception e) {
            e.printStackTrace();
            throw new DocumentServiceException("Error uploading file: " + file.getOriginalFilename());
        }
    }

    private Map<String, Object> uploadToProcessingService(MultipartFile file) {
        // This method is a placeholder for any additional processing service upload logic
        // You can implement it as needed

        File convFile = null;
        try {
            convFile = File.createTempFile("upload_", "_" + file.getOriginalFilename());
            file.transferTo(convFile);

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.MULTIPART_FORM_DATA);

            MultiValueMap<String, Object> body = new LinkedMultiValueMap<>();
            body.add("file", new FileSystemResource(convFile));

            HttpEntity<MultiValueMap<String, Object>> requestEntity = new HttpEntity<>(body, headers);

            ResponseEntity<HashMap<String, Object>> uploadResponse = restTemplate.exchange(
                    solrProcessorUrl + "/upload-pdf/",
                    org.springframework.http.HttpMethod.POST,
                    requestEntity,
                    new ParameterizedTypeReference<HashMap<String, Object>>() {}
            );

            return uploadResponse.getBody();
        } catch (Exception e) {
            logger.warn("Failed to upload to processing service: " + e.getMessage());
            e.printStackTrace();
            return null;
        } finally {
            if (convFile != null && convFile.exists()) {
                convFile.delete();
            }
        }
    }

    private String constructFilePath(String target, String targetId, String fileName) {
        StringBuilder filePath = new StringBuilder();

        // switch (target) {
        //     case PROCESS:
        //         // Example: filePath.append("process/").append(targetId).append("/").append(fileName);
        //         filePath.append("process/").append(targetId).append("/").append(fileName);
        //         break;
        //     case REGULATOR:
        //         // Example: filePath.append("regulator/").append(targetId).append("/").append(fileName);
        //         filePath.append("regulator/").append(targetId).append("/").append(fileName);
        //         break;
        //     case SERVICE:
        //         // Example: filePath.append("service/").append(targetId).append("/").append(fileName);
        //         filePath.append("service/").append(targetId).append("/").append(fileName);
        //         break;
        //     default:
        //         throw new IllegalArgumentException("Unsupported target type: " + target);
        // }

        return fileName;
    }

    @Override
    public ResponseEntity<?> handleUpload(String target, String targetId, String documentTypeId, MultipartFile file) {
        try {

            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            Jwt jwt = (Jwt) authentication.getPrincipal();

            System.out.println(jwt.getClaims());

            String username = jwt.getClaimAsString("preferred_username");

            DocumentDTO document = new DocumentDTO();
            document.setCreatedAt(LocalDateTime.now());
            document.setCreatedBy(username);
            document.setTarget(target);
            document.setOwnerId(targetId);
            document.setFilename(file.getOriginalFilename());
            String filePath = constructFilePath(target, targetId, file.getOriginalFilename());
            document.setUrl(uploadToMinio(file, filePath));

            document.setDocumentTypeId(documentTypeId);

            // Map<String, Object> solrResults = uploadToProcessingService(file);
            // document.setSummary(solrResults.get("summary").toString());
            // document.setSolrId(solrResults.get("document_id").toString());

            Optional<?> data = Optional.of(documentService.save(document));

            ResponseEntity<?> response;

            response = ResponseEntity.status(HttpStatus.OK).body(data.get());

            return response;
        } catch (Exception e) {
            e.printStackTrace();
            logger.error(e.getMessage());
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }
}