// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWS.java.vsl in andromda-webservices. Do not modify by hand!.
//
package bw.co.roguesystems.rfiles.document;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

public abstract class DocumentApiBase implements DocumentApi {

    protected Logger logger = LoggerFactory.getLogger(DocumentApi.class);
        protected final DocumentService documentService;

    public DocumentApiBase(
        DocumentService documentService    ) {
        this.documentService = documentService;
    }

    public ResponseEntity<?> downloadFile(String id) {
        return handleDownloadFile(id);
    }

    public abstract ResponseEntity<?> handleDownloadFile(String id);

    public ResponseEntity<?> findByDocumentType(String documentTypeId) {
        return handleFindByDocumentType(documentTypeId);
    }

    public abstract ResponseEntity<?> handleFindByDocumentType(String documentTypeId);

    public ResponseEntity<?> findById(String id) {
        return handleFindById(id);
    }

    public abstract ResponseEntity<?> handleFindById(String id);

    public ResponseEntity<?> findByTarget(String target, String targetId) {
        return handleFindByTarget(target, targetId);
    }

    public abstract ResponseEntity<?> handleFindByTarget(String target, String targetId);

    public ResponseEntity<?> getAll() {
        return handleGetAll();
    }

    public abstract ResponseEntity<?> handleGetAll();

    public ResponseEntity<?> getAllPaged(Integer pageNumber, Integer pageSize) {
        return handleGetAllPaged(pageNumber, pageSize);
    }

    public abstract ResponseEntity<?> handleGetAllPaged(Integer pageNumber, Integer pageSize);


    public ResponseEntity<?> remove(String id) {
        return handleRemove(id);
    }

    public abstract ResponseEntity<?> handleRemove(String id);


    public ResponseEntity<?> save(DocumentDTO document) {
        return handleSave(document);
    }

    public abstract ResponseEntity<?> handleSave(DocumentDTO document);


    public ResponseEntity<?> search(String criteria) {
        return handleSearch(criteria);
    }

    public abstract ResponseEntity<?> handleSearch(String criteria);


    public ResponseEntity<?> updateFile(String id, MultipartFile file) {
        return handleUpdateFile(id, file);
    }

    public abstract ResponseEntity<?> handleUpdateFile(String id, MultipartFile file);


    public ResponseEntity<?> upload(String target, String targetId, String documentTypeId, MultipartFile file) {
        return handleUpload(target, targetId, documentTypeId, file);
    }

    public abstract ResponseEntity<?> handleUpload(String target, String targetId, String documentTypeId, MultipartFile file);

    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return documentService
     */
    protected DocumentService getDocumentService()
    {
        return this.documentService;
    }

}