// license-header java merge-point
//
/**
 * @author Generated by ValueObject.vsl in andromda-java-cartridge on 07/23/2025 09:12:18+0200 Do not modify by hand!
 *
 * TEMPLATE:     ValueObject.vsl in andromda-java-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.roguesystems.rfiles::PropertySearchOrder
 * STEREOTYPE:   ValueObject
 */
package bw.co.roguesystems.rfiles;

// true

import java.io.Serializable;
import java.util.Arrays;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import org.apache.commons.lang3.builder.CompareToBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * TODO: Model Documentation for PropertySearchOrder
 */
@NoArgsConstructor
@Data
public class PropertySearchOrder
    implements Serializable, Comparable<PropertySearchOrder>
{
    /** The serial version UID of this class. Needed for serialization. */
    private static final long serialVersionUID = -7743868483535343254L;

    // Class attributes
    /**
     * TODO: Model Documentation for PropertySearchOrder.propertyName
     */
    @NonNull
    protected String propertyName;
    /**
     * TODO: Model Documentation for PropertySearchOrder.order
     */
    @NonNull
    protected SortOrder order;

    /**
     * Constructor with all properties
     * @param propertyNameIn String
     * @param orderIn SortOrder
     */
    public PropertySearchOrder(final String propertyNameIn, final SortOrder orderIn)
    {
        this.propertyName = propertyNameIn;
        this.order = orderIn;
    }

    /**
     * Copies constructor from other PropertySearchOrder
     *
     * @param otherBean Cannot be <code>null</code>
     * @throws NullPointerException if the argument is <code>null</code>
     */
    public PropertySearchOrder(final PropertySearchOrder otherBean)
    {
        this.propertyName = otherBean.getPropertyName();
        this.order = otherBean.getOrder();
    }

    /**
     * Copies all properties from the argument value object into this value object.
     * @param otherBean Cannot be <code>null</code>
     */
    public void copy(final PropertySearchOrder otherBean)
    {
        if (null != otherBean)
        {
            this.setPropertyName(otherBean.getPropertyName());
            this.setOrder(otherBean.getOrder());
        }
    }

    /**
     * @param object to compare this object against
     * @return boolean if equal
     * @see Object#equals(Object)
     */
    @Override
    public boolean equals(final Object object)
    {
        if (object==null || object.getClass() != this.getClass())
        {
             return false;
        }
        // Check if the same object instance
        if (object==this)
        {
            return true;
        }
        PropertySearchOrder rhs = (PropertySearchOrder) object;
        return new EqualsBuilder()
            .append(this.getPropertyName(), rhs.getPropertyName())
            .append(this.getOrder(), rhs.getOrder())
            .isEquals();
    }

    /**
     * @param object to compare this object against
     * @return int if equal
     * @see Comparable#compareTo(Object)
     */
    public int compareTo(final PropertySearchOrder object)
    {
        if (object==null)
        {
            return -1;
        }
        // Check if the same object instance
        if (object==this)
        {
            return 0;
        }
        return new CompareToBuilder()
            .append(this.getPropertyName(), object.getPropertyName())
            .append(this.getOrder(), object.getOrder())
            .toComparison();
    }

    /**
     * @return int hashCode value
     * @see Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        return new HashCodeBuilder(1249046965, -82296885)
            .append(this.getPropertyName())
            .append(this.getOrder())
            .toHashCode();
    }

    /**
     * @return String representation of object
     * @see Object#toString()
     */
    @Override
    public String toString()
    {

        StringBuilder builder = new StringBuilder();
        builder.append("{\n");
        builder.append("\t\"propertyName\" : \"" + this.getPropertyName() + "\"");
        builder.append("\t,\"order\" : \"" + this.getOrder() + "\"");
        builder.append("}");
        return builder.toString();

    }

    /**
     * Compares the properties of this instance to the properties of the argument. This method will return
     * {@code false} as soon as it detects that the argument is {@code null} or not of the same type as
     * (or a sub-type of) this instance's type.
     *
     * <p/>For array, collection or map properties the comparison will be done one level deep, in other words:
     * the elements will be compared using the {@code equals()} operation.
     *
     * <p/>Note that two properties will be considered equal when both values are {@code null}.
     *
     * @param thatObject the object containing the properties to compare against this instance
     * @return this method will return {@code true} in case the argument has the same type as this class, or is a
     *      sub-type of this class and all properties as found on this class have equal values when queried on that
     *      argument instance; in all other cases this method will return {@code false}
     */
    public boolean equalProperties(final Object thatObject)
    {
        if (thatObject == null || !this.getClass().isAssignableFrom(thatObject.getClass()))
        {
            return false;
        }

        final PropertySearchOrder that = (PropertySearchOrder)thatObject;
        return
            equal(this.getPropertyName(), that.getPropertyName())
            && equal(this.getOrder(), that.getOrder())
        ;
    }

    /**
     * This is a convenient helper method which is able to detect whether or not two values are equal. Two values
     * are equal when they are both {@code null}, are arrays of the same length with equal elements or are
     * equal objects (this includes {@link java.util.Collection} and {@link java.util.Map} instances).
     *
     * <p/>Note that for array, collection or map instances the comparison runs one level deep.
     *
     * @param first the first object to compare, may be {@code null}
     * @param second the second object to compare, may be {@code null}
     * @return this method will return {@code true} in case both objects are equal as explained above;
     *      in all other cases this method will return {@code false}
     */
    protected static boolean equal(final Object first, final Object second)
    {
        final boolean equal;

        if (first == null)
        {
            equal = (second == null);
        }
        else if (first.getClass().isArray() && (second != null) && second.getClass().isArray())
        {
            equal = Arrays.equals((Object[])first, (Object[])second);
        }
        else // note that the following also covers java.util.Collection and java.util.Map
        {
            equal = first.equals(second);
        }

        return equal;
    }

    // PropertySearchOrder value-object java merge-point
}