// license-header java merge-point
//
/**
 * @author Generated by ValueObject.vsl in andromda-java-cartridge on 07/23/2025 09:12:18+0200 Do not modify by hand!
 *
 * TEMPLATE:     ValueObject.vsl in andromda-java-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.roguesystems.rfiles::document::type::DocumentTypeDTO
 * STEREOTYPE:   FrontEndTable
 * STEREOTYPE:   ValueObject
 */
package bw.co.roguesystems.rfiles.document.type;

// true

import bw.co.roguesystems.rfiles.AuditableDTO;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import org.apache.commons.lang3.builder.CompareToBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * TODO: Model Documentation for DocumentTypeDTO
 */
@NoArgsConstructor
@Data
public class DocumentTypeDTO
    extends AuditableDTO
{
    /** The serial version UID of this class. Needed for serialization. */
    private static final long serialVersionUID = -3938513263570430268L;

    // Class attributes
    /**
     * TODO: Model Documentation for DocumentTypeDTO.code
     */
    @NonNull
    protected String code;
    /**
     * TODO: Model Documentation for DocumentTypeDTO.name
     */
    @NonNull
    protected String name;
    /**
     * TODO: Model Documentation for
     * DocumentTypeDTO.description
     */
    protected String description;

    /**
     * Constructor taking only required properties
     * @param codeIn String TODO: Model Documentation for DocumentTypeDTO.code
     * @param nameIn String TODO: Model Documentation for DocumentTypeDTO.name
     */
    public DocumentTypeDTO(final String codeIn, final String nameIn)
    {
        super();
        this.code = codeIn;
        this.name = nameIn;
    }

    /**
     * Constructor with all properties
     * @param idIn String
     * @param createdByIn String
     * @param createdAtIn LocalDateTime
     * @param modifiedByIn String
     * @param modifiedAtIn LocalDateTime
     * @param codeIn String
     * @param nameIn String
     * @param descriptionIn String
     */
    public DocumentTypeDTO(final String idIn, final String createdByIn, final LocalDateTime createdAtIn, final String modifiedByIn, final LocalDateTime modifiedAtIn, final String codeIn, final String nameIn, final String descriptionIn)
    {
        super(idIn, createdByIn, createdAtIn, modifiedByIn, modifiedAtIn);
        this.code = codeIn;
        this.name = nameIn;
        this.description = descriptionIn;
    }

    /**
     * Copies constructor from other DocumentTypeDTO
     *
     * @param otherBean Cannot be <code>null</code>
     * @throws NullPointerException if the argument is <code>null</code>
     */
    public DocumentTypeDTO(final DocumentTypeDTO otherBean)
    {
        super(otherBean);
        this.code = otherBean.getCode();
        this.name = otherBean.getName();
        this.description = otherBean.getDescription();
    }

    /**
     * Copies all properties from the argument value object into this value object.
     * @param otherBean Cannot be <code>null</code>
     */
    public void copy(final DocumentTypeDTO otherBean)
    {
        if (null != otherBean)
        {
            super.copy(otherBean);
            this.setCode(otherBean.getCode());
            this.setName(otherBean.getName());
            this.setDescription(otherBean.getDescription());
        }
    }

    /**
     * @param object to compare this object against
     * @return boolean if equal
     * @see Object#equals(Object)
     */
    @Override
    public boolean equals(final Object object)
    {
        if (object==null || object.getClass() != this.getClass())
        {
             return false;
        }
        // Check if the same object instance
        if (object==this)
        {
            return true;
        }
        DocumentTypeDTO rhs = (DocumentTypeDTO) object;
        return new EqualsBuilder()
            .appendSuper(super.equals(object))
            .append(this.getCode(), rhs.getCode())
            .append(this.getName(), rhs.getName())
            .append(this.getDescription(), rhs.getDescription())
            .isEquals();
    }

    /**
     * @param object to compare this object against
     * @return int if equal
     * @see Comparable#compareTo(Object)
     */
    public int compareTo(final AuditableDTO object)
    {
        if (object==null)
        {
            return -1;
        }
        // Check if the same object instance
        if (object==this)
        {
            return 0;
        }
        if (!(object instanceof DocumentTypeDTO))
        {
            return -1;
        }
        DocumentTypeDTO myClass = (DocumentTypeDTO)object;
        return new CompareToBuilder()
            .appendSuper(super.compareTo(object))
            .append(this.getCode(), myClass.getCode())
            .append(this.getName(), myClass.getName())
            .append(this.getDescription(), myClass.getDescription())
            .toComparison();
    }

    /**
     * @return int hashCode value
     * @see Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        return new HashCodeBuilder(1249046965, -82296885)
            .appendSuper(super.hashCode())
            .append(this.getCode())
            .append(this.getName())
            .append(this.getDescription())
            .toHashCode();
    }

    /**
     * @return String representation of object
     * @see Object#toString()
     */
    @Override
    public String toString()
    {

        StringBuilder builder = new StringBuilder();
        builder.append("{\n");
        builder.append("\t\"code\" : \"" + this.getCode() + "\"");
        builder.append("\t,\"name\" : \"" + this.getName() + "\"");
        builder.append("\t,\"description\" : \"" + this.getDescription() + "\"");
        builder.append("\t,\"id\" : \"" + this.getId() + "\"");
        builder.append("\t,\"createdBy\" : \"" + this.getCreatedBy() + "\"");
        builder.append("\t,\"createdAt\" : \"" + this.getCreatedAt() + "\"");
        builder.append("\t,\"modifiedBy\" : \"" + this.getModifiedBy() + "\"");
        builder.append("\t,\"modifiedAt\" : \"" + this.getModifiedAt() + "\"");
        builder.append("}");
        return builder.toString();

    }

    /**
     * Compares the properties of this instance to the properties of the argument. This method will return
     * {@code false} as soon as it detects that the argument is {@code null} or not of the same type as
     * (or a sub-type of) this instance's type.
     *
     * <p/>For array, collection or map properties the comparison will be done one level deep, in other words:
     * the elements will be compared using the {@code equals()} operation.
     *
     * <p/>Note that two properties will be considered equal when both values are {@code null}.
     *
     * @param thatObject the object containing the properties to compare against this instance
     * @return this method will return {@code true} in case the argument has the same type as this class, or is a
     *      sub-type of this class and all properties as found on this class have equal values when queried on that
     *      argument instance; in all other cases this method will return {@code false}
     */
    @Override
    public boolean equalProperties(final Object thatObject)
    {
        if (thatObject == null || !this.getClass().isAssignableFrom(thatObject.getClass()))
        {
            return false;
        }

        @SuppressWarnings("unchecked")
        final DocumentTypeDTO that = (DocumentTypeDTO)thatObject;
        return super.equalProperties(that)
            && equal(this.getCode(), that.getCode())
            && equal(this.getName(), that.getName())
            && equal(this.getDescription(), that.getDescription())
        ;
    }

    // DocumentTypeDTO value-object java merge-point
}