// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge on 07/23/2025 09:12:15+0200.
//
package bw.co.roguesystems.rfiles;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * TODO: Model Documentation for bw.co.roguesystems.rfiles.Auditable
 */
@MappedSuperclass
@Data
// HibernateEntity.vsl annotations merge-point
public abstract class Auditable
    implements Serializable{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6496144094265008779L;

    // Generate 5 attributes

    @Column(name = "CREATED_AT", unique = false, nullable = false, insertable = true, updatable = true)
    private LocalDateTime createdAt;


    @Column(name = "MODIFIED_AT", unique = false, nullable = true, insertable = true, updatable = true)
    private LocalDateTime modifiedAt;


    @Column(name = "CREATED_BY", unique = false, nullable = false, insertable = true, updatable = true)
    private String createdBy;


    @Column(name = "MODIFIED_BY", unique = false, nullable = true, insertable = true, updatable = true)
    private String modifiedBy;

// HibernateEntity.vsl merge-point
}