// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWS.java.vsl in andromda-webservices. Do not modify by hand!.
//
package bw.co.roguesystems.rfiles.document.type;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * 
 * TODO: Model Documentation for bw.co.roguesystems.fsrfp.document.type.DocumentTypeApi
 */
public interface DocumentTypeApi {

    @GetMapping("/{id}")
    public ResponseEntity<?> findById(@PathVariable(name = "id", required = true) String id);

    @GetMapping()
    public ResponseEntity<?> getAll();

    @GetMapping("/paged")
    public ResponseEntity<?> getAllPaged(@RequestParam(name = "pageNumber", required = false) Integer pageNumber, @RequestParam(name = "pageSize", required = false) Integer pageSize);

    @GetMapping("search/pageNumber/{pageNumber}/pageSize/{pageSize}")
    public ResponseEntity<?> pagedSearch(@RequestParam(name = "criteria", required = false) String criteria, @PathVariable(name = "pageNumber", required = false) Integer pageNumber, @PathVariable(name = "pageSize", required = false) Integer pageSize);

    @DeleteMapping("/{id}")
    public ResponseEntity<?> remove(@PathVariable(name = "id", required = true) String id);

    @PostMapping()
    public ResponseEntity<?> save(@RequestBody(required = true) DocumentTypeDTO documentType);

    @GetMapping("search")
    public ResponseEntity<?> search(@RequestParam(name = "criteria", required = false) String criteria);
}