// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWS.java.vsl in andromda-webservices. Do not modify by hand!.
//
package bw.co.roguesystems.rfiles.document.type;

import io.swagger.v3.oas.annotations.Operation;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;

public abstract class DocumentTypeApiBase implements DocumentTypeApi {

    protected Logger logger = LoggerFactory.getLogger(DocumentTypeApi.class);
        protected final DocumentTypeService documentTypeService;

    public DocumentTypeApiBase(
        DocumentTypeService documentTypeService    ) {
        this.documentTypeService = documentTypeService;
    }


    @GetMapping("/{id}")
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<?> findById(String id) {
        return handleFindById(id);
    }

    public abstract ResponseEntity<?> handleFindById(String id);


    @GetMapping()
    public ResponseEntity<?> getAll() {
        return handleGetAll();
    }

    public abstract ResponseEntity<?> handleGetAll();


    @GetMapping("/paged")
    public ResponseEntity<?> getAllPaged(Integer pageNumber, Integer pageSize) {
        return handleGetAllPaged(pageNumber, pageSize);
    }

    public abstract ResponseEntity<?> handleGetAllPaged(Integer pageNumber, Integer pageSize);


    @GetMapping("search/pageNumber/{pageNumber}/pageSize/{pageSize}")
    public ResponseEntity<?> pagedSearch(String criteria, Integer pageNumber, Integer pageSize) {
        return handlePagedSearch(criteria, pageNumber, pageSize);
    }

    public abstract ResponseEntity<?> handlePagedSearch(String criteria, Integer pageNumber, Integer pageSize);


    @DeleteMapping("/{id}")
    public ResponseEntity<?> remove(String id) {
        return handleRemove(id);
    }

    public abstract ResponseEntity<?> handleRemove(String id);


    @PostMapping()
    public ResponseEntity<?> save(DocumentTypeDTO documentType) {
        return handleSave(documentType);
    }

    public abstract ResponseEntity<?> handleSave(DocumentTypeDTO documentType);


    @GetMapping("search")
    public ResponseEntity<?> search(String criteria) {
        return handleSearch(criteria);
    }

    public abstract ResponseEntity<?> handleSearch(String criteria);

    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return documentTypeService
     */
    protected DocumentTypeService getDocumentTypeService()
    {
        return this.documentTypeService;
    }

}