// license-header java merge-point
//
/**
 * @author Generated by ValueObject.vsl in andromda-java-cartridge on 07/23/2025 09:12:18+0200 Do not modify by hand!
 *
 * TEMPLATE:     ValueObject.vsl in andromda-java-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.roguesystems.rfiles::document::DocumentDTO
 * STEREOTYPE:   ValueObject
 */
package bw.co.roguesystems.rfiles.document;

// true

import bw.co.roguesystems.rfiles.AuditableDTO;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import org.apache.commons.lang3.builder.CompareToBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * TODO: Model Documentation for DocumentDTO
 */
@NoArgsConstructor
@Data
public class DocumentDTO
    extends AuditableDTO
{
    /** The serial version UID of this class. Needed for serialization. */
    private static final long serialVersionUID = -3788598817534806906L;

    // Class attributes
    /**
     * TODO: Model Documentation for DocumentDTO.target
     */
    protected String target;
    /**
     * TODO: Model Documentation for DocumentDTO.owner
     */
    protected String owner;
    /**
     * TODO: Model Documentation for DocumentDTO.documentTypeId
     */
    protected String documentTypeId;
    /**
     * TODO: Model Documentation for DocumentDTO.documentType
     */
    protected String documentType;
    /**
     * TODO: Model Documentation for DocumentDTO.url
     */
    protected String url;
    /**
     * TODO: Model Documentation for DocumentDTO.summary
     */
    protected String summary;
    /**
     * TODO: Model Documentation for DocumentDTO.solrId
     */
    protected String solrId;
    /**
     * TODO: Model Documentation for DocumentDTO.filename
     */
    @NonNull
    protected String filename;
    /**
     * TODO: Model Documentation for DocumentDTO.ownerId
     */
    protected String ownerId;
    /**
     * TODO: Model Documentation for DocumentDTO.documentTypeCode
     */
    protected String documentTypeCode;

    /**
     * Constructor taking only required properties
     * @param filenameIn String TODO: Model Documentation for DocumentDTO.filename
     */
    public DocumentDTO(final String filenameIn)
    {
        super();
        this.filename = filenameIn;
    }

    /**
     * Constructor with all properties
     * @param idIn String
     * @param createdByIn String
     * @param createdAtIn LocalDateTime
     * @param modifiedByIn String
     * @param modifiedAtIn LocalDateTime
     * @param targetIn String
     * @param ownerIn String
     * @param documentTypeIdIn String
     * @param documentTypeIn String
     * @param urlIn String
     * @param summaryIn String
     * @param solrIdIn String
     * @param filenameIn String
     * @param ownerIdIn String
     * @param documentTypeCodeIn String
     */
    public DocumentDTO(final String idIn, final String createdByIn, final LocalDateTime createdAtIn, final String modifiedByIn, final LocalDateTime modifiedAtIn, final String targetIn, final String ownerIn, final String documentTypeIdIn, final String documentTypeIn, final String urlIn, final String summaryIn, final String solrIdIn, final String filenameIn, final String ownerIdIn, final String documentTypeCodeIn)
    {
        super(idIn, createdByIn, createdAtIn, modifiedByIn, modifiedAtIn);
        this.target = targetIn;
        this.owner = ownerIn;
        this.documentTypeId = documentTypeIdIn;
        this.documentType = documentTypeIn;
        this.url = urlIn;
        this.summary = summaryIn;
        this.solrId = solrIdIn;
        this.filename = filenameIn;
        this.ownerId = ownerIdIn;
        this.documentTypeCode = documentTypeCodeIn;
    }

    /**
     * Copies constructor from other DocumentDTO
     *
     * @param otherBean Cannot be <code>null</code>
     * @throws NullPointerException if the argument is <code>null</code>
     */
    public DocumentDTO(final DocumentDTO otherBean)
    {
        super(otherBean);
        this.target = otherBean.getTarget();
        this.owner = otherBean.getOwner();
        this.documentTypeId = otherBean.getDocumentTypeId();
        this.documentType = otherBean.getDocumentType();
        this.url = otherBean.getUrl();
        this.summary = otherBean.getSummary();
        this.solrId = otherBean.getSolrId();
        this.filename = otherBean.getFilename();
        this.ownerId = otherBean.getOwnerId();
        this.documentTypeCode = otherBean.getDocumentTypeCode();
    }

    /**
     * Copies all properties from the argument value object into this value object.
     * @param otherBean Cannot be <code>null</code>
     */
    public void copy(final DocumentDTO otherBean)
    {
        if (null != otherBean)
        {
            super.copy(otherBean);
            this.setTarget(otherBean.getTarget());
            this.setOwner(otherBean.getOwner());
            this.setDocumentTypeId(otherBean.getDocumentTypeId());
            this.setDocumentType(otherBean.getDocumentType());
            this.setUrl(otherBean.getUrl());
            this.setSummary(otherBean.getSummary());
            this.setSolrId(otherBean.getSolrId());
            this.setFilename(otherBean.getFilename());
            this.setOwnerId(otherBean.getOwnerId());
            this.setDocumentTypeCode(otherBean.getDocumentTypeCode());
        }
    }

    /**
     * @param object to compare this object against
     * @return boolean if equal
     * @see Object#equals(Object)
     */
    @Override
    public boolean equals(final Object object)
    {
        if (object==null || object.getClass() != this.getClass())
        {
             return false;
        }
        // Check if the same object instance
        if (object==this)
        {
            return true;
        }
        DocumentDTO rhs = (DocumentDTO) object;
        return new EqualsBuilder()
            .appendSuper(super.equals(object))
            .append(this.getTarget(), rhs.getTarget())
            .append(this.getOwner(), rhs.getOwner())
            .append(this.getDocumentTypeId(), rhs.getDocumentTypeId())
            .append(this.getDocumentType(), rhs.getDocumentType())
            .append(this.getUrl(), rhs.getUrl())
            .append(this.getSummary(), rhs.getSummary())
            .append(this.getSolrId(), rhs.getSolrId())
            .append(this.getFilename(), rhs.getFilename())
            .append(this.getOwnerId(), rhs.getOwnerId())
            .append(this.getDocumentTypeCode(), rhs.getDocumentTypeCode())
            .isEquals();
    }

    /**
     * @param object to compare this object against
     * @return int if equal
     * @see Comparable#compareTo(Object)
     */
    public int compareTo(final AuditableDTO object)
    {
        if (object==null)
        {
            return -1;
        }
        // Check if the same object instance
        if (object==this)
        {
            return 0;
        }
        if (!(object instanceof DocumentDTO))
        {
            return -1;
        }
        DocumentDTO myClass = (DocumentDTO)object;
        return new CompareToBuilder()
            .appendSuper(super.compareTo(object))
            .append(this.getTarget(), myClass.getTarget())
            .append(this.getOwner(), myClass.getOwner())
            .append(this.getDocumentTypeId(), myClass.getDocumentTypeId())
            .append(this.getDocumentType(), myClass.getDocumentType())
            .append(this.getUrl(), myClass.getUrl())
            .append(this.getSummary(), myClass.getSummary())
            .append(this.getSolrId(), myClass.getSolrId())
            .append(this.getFilename(), myClass.getFilename())
            .append(this.getOwnerId(), myClass.getOwnerId())
            .append(this.getDocumentTypeCode(), myClass.getDocumentTypeCode())
            .toComparison();
    }

    /**
     * @return int hashCode value
     * @see Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        return new HashCodeBuilder(1249046965, -82296885)
            .appendSuper(super.hashCode())
            .append(this.getTarget())
            .append(this.getOwner())
            .append(this.getDocumentTypeId())
            .append(this.getDocumentType())
            .append(this.getUrl())
            .append(this.getSummary())
            .append(this.getSolrId())
            .append(this.getFilename())
            .append(this.getOwnerId())
            .append(this.getDocumentTypeCode())
            .toHashCode();
    }

    /**
     * @return String representation of object
     * @see Object#toString()
     */
    @Override
    public String toString()
    {

        StringBuilder builder = new StringBuilder();
        builder.append("{\n");
        builder.append("\t\"target\" : \"" + this.getTarget() + "\"");
        builder.append("\t,\"owner\" : \"" + this.getOwner() + "\"");
        builder.append("\t,\"documentTypeId\" : \"" + this.getDocumentTypeId() + "\"");
        builder.append("\t,\"documentType\" : \"" + this.getDocumentType() + "\"");
        builder.append("\t,\"url\" : \"" + this.getUrl() + "\"");
        builder.append("\t,\"summary\" : \"" + this.getSummary() + "\"");
        builder.append("\t,\"solrId\" : \"" + this.getSolrId() + "\"");
        builder.append("\t,\"filename\" : \"" + this.getFilename() + "\"");
        builder.append("\t,\"ownerId\" : \"" + this.getOwnerId() + "\"");
        builder.append("\t,\"documentTypeCode\" : \"" + this.getDocumentTypeCode() + "\"");
        builder.append("\t,\"id\" : \"" + this.getId() + "\"");
        builder.append("\t,\"createdBy\" : \"" + this.getCreatedBy() + "\"");
        builder.append("\t,\"createdAt\" : \"" + this.getCreatedAt() + "\"");
        builder.append("\t,\"modifiedBy\" : \"" + this.getModifiedBy() + "\"");
        builder.append("\t,\"modifiedAt\" : \"" + this.getModifiedAt() + "\"");
        builder.append("}");
        return builder.toString();

    }

    /**
     * Compares the properties of this instance to the properties of the argument. This method will return
     * {@code false} as soon as it detects that the argument is {@code null} or not of the same type as
     * (or a sub-type of) this instance's type.
     *
     * <p/>For array, collection or map properties the comparison will be done one level deep, in other words:
     * the elements will be compared using the {@code equals()} operation.
     *
     * <p/>Note that two properties will be considered equal when both values are {@code null}.
     *
     * @param thatObject the object containing the properties to compare against this instance
     * @return this method will return {@code true} in case the argument has the same type as this class, or is a
     *      sub-type of this class and all properties as found on this class have equal values when queried on that
     *      argument instance; in all other cases this method will return {@code false}
     */
    @Override
    public boolean equalProperties(final Object thatObject)
    {
        if (thatObject == null || !this.getClass().isAssignableFrom(thatObject.getClass()))
        {
            return false;
        }

        @SuppressWarnings("unchecked")
        final DocumentDTO that = (DocumentDTO)thatObject;
        return super.equalProperties(that)
            && equal(this.getTarget(), that.getTarget())
            && equal(this.getOwner(), that.getOwner())
            && equal(this.getDocumentTypeId(), that.getDocumentTypeId())
            && equal(this.getDocumentType(), that.getDocumentType())
            && equal(this.getUrl(), that.getUrl())
            && equal(this.getSummary(), that.getSummary())
            && equal(this.getSolrId(), that.getSolrId())
            && equal(this.getFilename(), that.getFilename())
            && equal(this.getOwnerId(), that.getOwnerId())
            && equal(this.getDocumentTypeCode(), that.getDocumentTypeCode())
        ;
    }

    // DocumentDTO value-object java merge-point
}