// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringRepository.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.rfiles.document.type;

import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

public interface DocumentTypeRepository extends 
        JpaRepository<DocumentType, String>,
        JpaSpecificationExecutor<DocumentType> {

    // Generating pageable query method for code
    DocumentType findByCode(String code);

    Page<DocumentType> findByCode(String code, Pageable pageable);

    Page<DocumentType> findByCodeStartingWithIgnoreCase(String code, Pageable pageable);
    
    Page<DocumentType> findByCodeEndingWithIgnoreCase(String code, Pageable pageable);
    
    Page<DocumentType> findByCodeContainingIgnoreCase(String code, Pageable pageable);
    
    Page<DocumentType> findByCodeLikeIgnoreCase(String code, Pageable pageable);
    
    Page<DocumentType> findByCodeNotLikeIgnoreCase(String code, Pageable pageable);
    
    Page<DocumentType> findByCodeContaining(String code, Pageable pageable);
    
    // Search by a list of parameters
    List<DocumentType> findByCodeNot(String code);
    Page<DocumentType> findByCodeNot(String code, Pageable pageable);
    
    List<DocumentType> findByCodeIn(List<String> codes);
    Page<DocumentType> findByCodeIn(List<String> codes, Pageable pageable);
    
    List<DocumentType> findByCodeNotIn(List<String> codes);
    Page<DocumentType> findByCodeNotIn(List<String> codes, Pageable pageable);

    // Generating pageable query method for name
    DocumentType findByName(String name);

    Page<DocumentType> findByName(String name, Pageable pageable);

    Page<DocumentType> findByNameStartingWithIgnoreCase(String name, Pageable pageable);
    
    Page<DocumentType> findByNameEndingWithIgnoreCase(String name, Pageable pageable);
    
    Page<DocumentType> findByNameContainingIgnoreCase(String name, Pageable pageable);
    
    Page<DocumentType> findByNameLikeIgnoreCase(String name, Pageable pageable);
    
    Page<DocumentType> findByNameNotLikeIgnoreCase(String name, Pageable pageable);
    
    Page<DocumentType> findByNameContaining(String name, Pageable pageable);
    
    // Search by a list of parameters
    List<DocumentType> findByNameNot(String name);
    Page<DocumentType> findByNameNot(String name, Pageable pageable);
    
    List<DocumentType> findByNameIn(List<String> names);
    Page<DocumentType> findByNameIn(List<String> names, Pageable pageable);
    
    List<DocumentType> findByNameNotIn(List<String> names);
    Page<DocumentType> findByNameNotIn(List<String> names, Pageable pageable);

    // Generating pageable query method for description
    Page<DocumentType> findByDescriptionNull(Pageable pageable);

    Page<DocumentType> findByDescriptionStartingWithIgnoreCase(String description, Pageable pageable);
    
    Page<DocumentType> findByDescriptionEndingWithIgnoreCase(String description, Pageable pageable);
    
    Page<DocumentType> findByDescriptionContainingIgnoreCase(String description, Pageable pageable);
    
    Page<DocumentType> findByDescriptionLikeIgnoreCase(String description, Pageable pageable);
    
    Page<DocumentType> findByDescriptionNotLikeIgnoreCase(String description, Pageable pageable);
    
    Page<DocumentType> findByDescriptionContaining(String description, Pageable pageable);
    
    // Search by a list of parameters
    List<DocumentType> findByDescriptionNot(String description);
    Page<DocumentType> findByDescriptionNot(String description, Pageable pageable);
    
    List<DocumentType> findByDescriptionIn(List<String> descriptions);
    Page<DocumentType> findByDescriptionIn(List<String> descriptions, Pageable pageable);
    
    List<DocumentType> findByDescriptionNotIn(List<String> descriptions);
    Page<DocumentType> findByDescriptionNotIn(List<String> descriptions, Pageable pageable);

    // Generating pageable query method for id
    Page<DocumentType> findByIdNull(Pageable pageable);

    Page<DocumentType> findByIdStartingWithIgnoreCase(String id, Pageable pageable);
    
    Page<DocumentType> findByIdEndingWithIgnoreCase(String id, Pageable pageable);
    
    Page<DocumentType> findByIdContainingIgnoreCase(String id, Pageable pageable);
    
    Page<DocumentType> findByIdLikeIgnoreCase(String id, Pageable pageable);
    
    Page<DocumentType> findByIdNotLikeIgnoreCase(String id, Pageable pageable);
    
    Page<DocumentType> findByIdContaining(String id, Pageable pageable);
    
    // Search by a list of parameters
    List<DocumentType> findByIdNot(String id);
    Page<DocumentType> findByIdNot(String id, Pageable pageable);
    
    List<DocumentType> findByIdIn(List<String> ids);
    Page<DocumentType> findByIdIn(List<String> ids, Pageable pageable);
    
    List<DocumentType> findByIdNotIn(List<String> ids);
    Page<DocumentType> findByIdNotIn(List<String> ids, Pageable pageable);

}