// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by HibernateEntityImpl.vsl in andromda-hibernate-cartridge on 07/23/2025 09:12:15+0200.
//
package bw.co.roguesystems.rfiles.document.type;

/**
 * @see DocumentType
 */
// HibernateEntityImpl.vsl annotations merge-point
public class DocumentTypeImpl
    extends DocumentType
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1347597045121951071L;

// HibernateEntityImpl.vsl merge-point
}