// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringServiceBase.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
/**
 * TEMPLATE:    SpringServiceBase.vsl in andromda-spring cartridge
 * MODEL CLASS: AndroMDAModel::backend::bw.co.roguesystems.rfiles::document::type::DocumentTypeService
 * STEREOTYPE:  Service
 */
package bw.co.roguesystems.rfiles.document.type;

import java.security.Principal;
import java.util.Collection;
import java.util.Locale;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Page;

/**
 * <p>
 * Spring Service base class for <code>DocumentTypeService</code>,
 * provides access to all services and entities referenced by this service.
 * </p>
 *
 * @see DocumentTypeService
 */
public abstract class DocumentTypeServiceBase
    implements DocumentTypeService
{
    protected Logger logger = LoggerFactory.getLogger(DocumentTypeService.class);
    protected final DocumentTypeDao documentTypeDao;
    protected final DocumentTypeRepository documentTypeRepository;
    protected final MessageSource messageSource;

    public DocumentTypeServiceBase(
        DocumentTypeDao documentTypeDao,
        DocumentTypeRepository documentTypeRepository,
        MessageSource messageSource
    ) {
        this.documentTypeDao = documentTypeDao;
        this.documentTypeRepository = documentTypeRepository;
        this.messageSource = messageSource;
    }

	/**
     * Gets the reference to <code>documentType</code>'s DAO.
     * @return documentTypeDao
     */
    protected DocumentTypeDao getDocumentTypeDao()
    {
        return this.documentTypeDao;
    }

    /**
     * Gets the reference to <code>documentType</code>'s repository.
     * @return documentTypeRepository
     */
    public DocumentTypeRepository getDocumentTypeRepository() {
        return documentTypeRepository;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentTypeDTO findById(final String id)
    {
        if (id == null || id.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.type.DocumentTypeService.findById(String id) - 'id' can not be null or empty");
        }
        try
        {
            return this.handleFindById(id);
        }
        catch (Throwable th)
        {
            throw new DocumentTypeServiceException(
                "Error performing 'DocumentTypeService.findById(String id)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #findById(String)}
     * @param id String TODO: Model Documentation for
DocumentTypeService.findById(id)
     * @return DocumentTypeDTO
     * @throws Exception
     */
    protected abstract DocumentTypeDTO handleFindById(String id)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentTypeDTO save(final DocumentTypeDTO documentType)
    {
        if (documentType == null)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.type.DocumentTypeService.save(DocumentTypeDTO documentType) - 'documentType' can not be null");
        }
        if (documentType.getCode() == null || documentType.getCode().trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.type.DocumentTypeService.save(DocumentTypeDTO documentType) - 'documentType.code' can not be null or empty");
        }
        if (documentType.getName() == null || documentType.getName().trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.type.DocumentTypeService.save(DocumentTypeDTO documentType) - 'documentType.name' can not be null or empty");
        }
        try
        {
            return this.handleSave(documentType);
        }
        catch (Throwable th)
        {
            throw new DocumentTypeServiceException(
                "Error performing 'DocumentTypeService.save(DocumentTypeDTO documentType)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #save(DocumentTypeDTO)}
     * @param documentType DocumentTypeDTO TODO: Model Documentation for
DocumentTypeService.save(documentType)
     * @return DocumentTypeDTO
     * @throws Exception
     */
    protected abstract DocumentTypeDTO handleSave(DocumentTypeDTO documentType)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean remove(final String id)
    {
        if (id == null || id.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.type.DocumentTypeService.remove(String id) - 'id' can not be null or empty");
        }
        try
        {
            return this.handleRemove(id);
        }
        catch (Throwable th)
        {
            throw new DocumentTypeServiceException(
                "Error performing 'DocumentTypeService.remove(String id)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #remove(String)}
     * @param id String TODO: Model Documentation for DocumentTypeService.remove(id)
     * @return boolean
     * @throws Exception
     */
    protected abstract boolean handleRemove(String id)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Collection<DocumentTypeDTO> getAll()
    {
        try
        {
            return this.handleGetAll();
        }
        catch (Throwable th)
        {
            throw new DocumentTypeServiceException(
                "Error performing 'DocumentTypeService.getAll()' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #getAll()}
     * @return Collection<DocumentTypeDTO>
     * @throws Exception
     */
    protected abstract Collection<DocumentTypeDTO> handleGetAll()
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Collection<DocumentTypeDTO> search(final String criteria)
    {
        if (criteria == null || criteria.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.type.DocumentTypeService.search(String criteria) - 'criteria' can not be null or empty");
        }
        try
        {
            return this.handleSearch(criteria);
        }
        catch (Throwable th)
        {
            throw new DocumentTypeServiceException(
                "Error performing 'DocumentTypeService.search(String criteria)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #search(String)}
     * @param criteria String TODO: Model Documentation for
DocumentTypeService.search(criteria)
     * @return Collection<DocumentTypeDTO>
     * @throws Exception
     */
    protected abstract Collection<DocumentTypeDTO> handleSearch(String criteria)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Page<DocumentTypeDTO> getAll(final Integer pageNumber, final Integer pageSize)
    {
        try
        {
            return this.handleGetAll(pageNumber, pageSize);
        }
        catch (Throwable th)
        {
            throw new DocumentTypeServiceException(
                "Error performing 'DocumentTypeService.getAll(Integer pageNumber, Integer pageSize)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #getAll(Integer, Integer)}
     * @param pageNumber Integer TODO: Model Documentation for
DocumentTypeService.getAll(pageNumber)
     * @param pageSize Integer TODO: Model Documentation for
DocumentTypeService.getAll(pageSize)
     * @return Page<DocumentTypeDTO>
     * @throws Exception
     */
    protected abstract Page<DocumentTypeDTO> handleGetAll(Integer pageNumber, Integer pageSize)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Page<DocumentTypeDTO> search(final String criteria, final Integer pageNumber, final Integer pageSize)
    {
        if (criteria == null || criteria.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.type.DocumentTypeService.search(String criteria, Integer pageNumber, Integer pageSize) - 'criteria' can not be null or empty");
        }
        try
        {
            return this.handleSearch(criteria, pageNumber, pageSize);
        }
        catch (Throwable th)
        {
            throw new DocumentTypeServiceException(
                "Error performing 'DocumentTypeService.search(String criteria, Integer pageNumber, Integer pageSize)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #search(String, Integer, Integer)}
     * @param criteria String TODO: Model Documentation for
DocumentTypeService.search(criteria)
     * @param pageNumber Integer TODO: Model Documentation for
DocumentTypeService.search(pageNumber)
     * @param pageSize Integer TODO: Model Documentation for
DocumentTypeService.search(pageSize)
     * @return Page<DocumentTypeDTO>
     * @throws Exception
     */
    protected abstract Page<DocumentTypeDTO> handleSearch(String criteria, Integer pageNumber, Integer pageSize)
        throws Exception;

    /**
     * Gets the message source available to this service.
     * @return MessageSource
     */
    protected MessageSource getMessages()
    {
        return messageSource;
    }

    /**
     * Gets the message having the given <code>key</code> in the underlying message bundle.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @return String
     */
    protected String getMessage(final String key)
    {
        return this.getMessages().getMessage(key, null, null);
    }

    /**
     * Gets the message having the given <code>key</code> and <code>arguments</code> in the
     * underlying message bundle.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @param arguments any arguments to substitute when resolving the message.
     * @return String
     */
    protected String getMessage(final String key, final Object[] arguments)
    {
        return this.getMessages().getMessage(key, arguments, null);
    }

    /**
     * Gets the message having the given <code>key</code> using the given <code>arguments</code>
     * for the given <code>locale</code>.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @param arguments any arguments to substitute when resolving the message.
     * @param locale the locale of the messages to retrieve.
     * @return String
     */
    protected String getMessage(
        final String key, final Object[] arguments,
        final Locale locale)
    {
        return this.getMessages().getMessage(key, arguments, locale);
    }


// spring-service-base merge-point
}