// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand! hibernate4or5=true hibernateVersion=6.1.6.Final
// Generated by hibernate/SpringHibernateDaoBase.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.rfiles.document.type;

import java.security.Principal;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.collections4.Transformer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>DocumentType</code>.
 * </p>
 *
 * @see DocumentType
 */
public abstract class DocumentTypeDaoBase
    implements DocumentTypeDao
{

    protected final Logger logger = LoggerFactory.getLogger(DocumentTypeDaoBase.class);

    protected final DocumentTypeRepository documentTypeRepository;

    public DocumentTypeDaoBase(
        DocumentTypeRepository documentTypeRepository
    ) {
        this.documentTypeRepository = documentTypeRepository;
    }




        


    /**
     * {@inheritDoc}
     */
    @Override
    public Collection<DocumentType> findByCriteria(final String criteria)
    {
        if (criteria == null)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.type.DocumentTypeDao.findByCriteria(String criteria) - 'criteria' can not be null");
        }
        try
        {
            return this.handleFindByCriteria(criteria);
        }
        catch (Throwable th)
        {
            throw new RuntimeException(
            "Error performing 'DocumentTypeDao.findByCriteria(String criteria)' --> " + th,
            th);
        }
    }

    /**
     * Performs the core logic for {@link #findByCriteria(String)}
     * @param criteria
     * @return Collection<DocumentType>
     * @throws Exception
     */
    protected abstract Collection<DocumentType> handleFindByCriteria(String criteria)
        throws Exception;

    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>DocumentTypeDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     * <p>
     * This method will return instances of these types:
     * <ul>
     *   <li>{@link DocumentType} - {@link #TRANSFORM_NONE}</li>
     *   <li>{@link DocumentTypeDTO} - {@link #TRANSFORM_DOCUMENTTYPEDTO}</li>
     * </ul>
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link DocumentTypeDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see DocumentTypeDao#transformEntity(int, DocumentType)
     */
    @Override
    public Object transformEntity(final int transform, final DocumentType entity)
    {
        Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_DOCUMENTTYPEDTO :
                    target = toDocumentTypeDTO(entity);
                    break;
                case DocumentTypeDao.TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void transformEntities(final int transform, final Collection<?> entities)
    {
        switch (transform)
        {
            case TRANSFORM_DOCUMENTTYPEDTO :
                CollectionUtils.transform(entities, this.DOCUMENTTYPEDTO_TRANSFORMER);
                break;
            case DocumentTypeDao.TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

    /**
     * @see DocumentTypeDao#toEntities(Collection)
     */
    @Override
    public void toEntities(final Collection<?> results)
    {
        if (results != null)
        {
            CollectionUtils.transform(results, this.ENTITYTRANSFORMER);
        }
    }

    /**
     * This anonymous transformer is designed to transform report query results
     * (which result in an array of entities) to {@link DocumentType}
     * using the Jakarta Commons-Collections Transformation API.
     */
    private Transformer ENTITYTRANSFORMER =
        new Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                Object result = null;
                if (input instanceof Object[])
                {
                    final Object[] rows = (Object[])input;
                    result = toEntity(rows);
                }
                else if (input instanceof DocumentType)
                {
                    result = input;
                }
                return result;
            }
        };

    /**
     * @param row
     * @return DocumentType
     */
    protected DocumentType toEntity(Object[] row)
    {
        DocumentType target = null;
        if (row != null)
        {
            final int numberOfObjects = row.length;
            for (int ctr = 0; ctr < numberOfObjects; ctr++)
            {
                final Object object = row[ctr];
                if (object instanceof DocumentType)
                {
                    target = (DocumentType)object;
                    break;
                }
            }
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({"unchecked"})
    public Collection<DocumentTypeDTO> toDocumentTypeDTOCollection(Collection<DocumentType> entities)
    {
        if (entities == null)
        {
            return null;
        }
        @SuppressWarnings("rawtypes")
        Collection result = new ArrayList(entities);
        CollectionUtils.transform(result, this.DOCUMENTTYPEDTO_TRANSFORMER);
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({ "unchecked" })
    public DocumentTypeDTO[] toDocumentTypeDTOArray(Collection<?> entities)
    {
        DocumentTypeDTO[] result = null;
        if (entities != null)
        {
        @SuppressWarnings("rawtypes")
            final Collection collection = new ArrayList(entities);
            this.toDocumentTypeDTOCollection(collection);
            result = (DocumentTypeDTO[]) collection.toArray(new DocumentTypeDTO[collection.size()]);
        }
        return result;
    }

    /**
     * Default implementation for transforming the results of a report query into a value object. This
     * implementation exists for convenience reasons only. It needs only be overridden in the
     * {@link DocumentTypeDaoImpl} class if you intend to use reporting queries.
     * @param row
     * @return toDocumentTypeDTO(this.toEntity(row))
     * @see DocumentTypeDao#toDocumentTypeDTO(DocumentType)
     */
    protected DocumentTypeDTO toDocumentTypeDTO(Object[] row)
    {
        return this.toDocumentTypeDTO(this.toEntity(row));
    }

    /**
     * This anonymous transformer is designed to transform entities or report query results
     * (which result in an array of objects) to {@link DocumentTypeDTO}
     * using the Jakarta Commons-Collections Transformation API.
     */
    private Transformer DOCUMENTTYPEDTO_TRANSFORMER =
        new Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                Object result = null;
                if (input instanceof DocumentType)
                {
                    final DocumentType entity = (DocumentType)input;
                    result = toDocumentTypeDTO(entity);
                }
                else if (input instanceof Object[])
                {
                    final Object[] rows = (Object[])input;
                    result = toDocumentTypeDTO(rows);
                }
                return result;
            }
        };

    /**
     * {@inheritDoc}
     */
    @Override
    public void documentTypeDTOToEntityCollection(Collection<?> instances)
    {
        if (instances != null)
        {
            for (final Iterator<?> iterator = instances.iterator(); iterator.hasNext();)
            {
                // - remove an objects that are null or not of the correct instance
                if (!(iterator.next() instanceof DocumentTypeDTO))
                {
                    iterator.remove();
                }
            }
            CollectionUtils.transform(instances, this.DocumentTypeDTOToEntityTransformer);
        }
    }

    private final Transformer DocumentTypeDTOToEntityTransformer =
        new Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                return documentTypeDTOToEntity((DocumentTypeDTO)input);
            }
        };


    /**
     * {@inheritDoc}
     */
    @Override
    public void toDocumentTypeDTO(
        DocumentType source,
        DocumentTypeDTO target)
    {
        // No conversion for target.id (can't convert source.getId():java.lang.Long to String)
        target.setId(source.getId());
        target.setCreatedBy(source.getCreatedBy());
        target.setCreatedAt(source.getCreatedAt());
        target.setModifiedBy(source.getModifiedBy());
        target.setModifiedAt(source.getModifiedAt());
        target.setCode(source.getCode());
        target.setName(source.getName());
        target.setDescription(source.getDescription());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentTypeDTO toDocumentTypeDTO(final DocumentType entity)
    {
        DocumentTypeDTO target = null;
        if (entity != null)
        {
            target =  new DocumentTypeDTO();
            this.toDocumentTypeDTO(entity, target);
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void documentTypeDTOToEntity(
        DocumentTypeDTO source,
        DocumentType target,
        boolean copyIfNull)
    {
        if (copyIfNull || source.getCode() != null)
        {
            target.setCode(source.getCode());
        }
        if (copyIfNull || source.getName() != null)
        {
            target.setName(source.getName());
        }
        if (copyIfNull || source.getDescription() != null)
        {
            target.setDescription(source.getDescription());
        }
        if (copyIfNull || source.getCreatedAt() != null)
        {
            target.setCreatedAt(source.getCreatedAt());
        }
        if (copyIfNull || source.getModifiedAt() != null)
        {
            target.setModifiedAt(source.getModifiedAt());
        }
        if (copyIfNull || source.getCreatedBy() != null)
        {
            target.setCreatedBy(source.getCreatedBy());
        }
        if (copyIfNull || source.getModifiedBy() != null)
        {
            target.setModifiedBy(source.getModifiedBy());
        }
    }

    // spring-hibernate-dao-base merge-point
}