// license-header java merge-point
//
/**
 * @author Generated by Service.vsl in andromda-java-cartridge on 07/23/2025 09:12:17+0200 Do not modify by hand!
 *
 * TEMPLATE:     Service.vsl in andromda-java-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.roguesystems.rfiles::document::type::DocumentTypeService
 * STEREOTYPE:   Service
 */
package bw.co.roguesystems.rfiles.document.type;

import java.util.Collection;
import org.springframework.data.domain.Page;

/**
 * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.type.DocumentTypeService
 */
public interface DocumentTypeService
{
    /**
     * TODO: Model Documentation for
     * bw.co.roguesystems.rfiles.document.type.DocumentTypeService.findById
     * @param id TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.type.DocumentTypeService.findById(id)
     * @return DocumentTypeDTO
     */
    public DocumentTypeDTO findById(String id) ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.type.DocumentTypeService.save
     * @param documentType TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.type.DocumentTypeService.save(documentType)
     * @return DocumentTypeDTO
     */
    public DocumentTypeDTO save(DocumentTypeDTO documentType) ;

    /**
     * TODO: Model Documentation for
     * bw.co.roguesystems.rfiles.document.type.DocumentTypeService.remove
     * @param id TODO: Model Documentation for bw.co.roguesystems.rfiles.document.type.DocumentTypeService.remove(id)
     * @return boolean
     */
    public boolean remove(String id) ;

    /**
     * TODO: Model Documentation for
     * bw.co.roguesystems.rfiles.document.type.DocumentTypeService.getAll
     * @return Collection<DocumentTypeDTO>
     */
    public Collection<DocumentTypeDTO> getAll() ;

    /**
     * TODO: Model Documentation for
     * bw.co.roguesystems.rfiles.document.type.DocumentTypeService.search
     * @param criteria TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.type.DocumentTypeService.search(criteria)
     * @return Collection<DocumentTypeDTO>
     */
    public Collection<DocumentTypeDTO> search(String criteria) ;

    /**
     * TODO: Model Documentation for
     * bw.co.roguesystems.rfiles.document.type.DocumentTypeService.getAll
     * @param pageNumber TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.type.DocumentTypeService.getAll(pageNumber)
     * @param pageSize TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.type.DocumentTypeService.getAll(pageSize)
     * @return Page<DocumentTypeDTO>
     */
    public Page<DocumentTypeDTO> getAll(Integer pageNumber, Integer pageSize) ;

    /**
     * TODO: Model Documentation for
     * bw.co.roguesystems.rfiles.document.type.DocumentTypeService.search
     * @param criteria TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.type.DocumentTypeService.search(criteria)
     * @param pageNumber TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.type.DocumentTypeService.search(pageNumber)
     * @param pageSize TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.type.DocumentTypeService.search(pageSize)
     * @return Page<DocumentTypeDTO>
     */
    public Page<DocumentTypeDTO> search(String criteria, Integer pageNumber, Integer pageSize) ;

}