// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand! hibernate4or5=true hibernateVersion=6.1.6.Final
// Generated by hibernate/SpringHibernateDaoBase.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.rfiles.document;

import bw.co.roguesystems.rfiles.document.type.DocumentTypeDao;
import bw.co.roguesystems.rfiles.document.type.DocumentTypeRepository;
import java.security.Principal;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.collections4.Transformer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>Document</code>.
 * </p>
 *
 * @see Document
 */
public abstract class DocumentDaoBase
    implements DocumentDao
{

    protected final Logger logger = LoggerFactory.getLogger(DocumentDaoBase.class);

    protected final DocumentRepository documentRepository;

    protected DocumentTypeDao documentTypeDao;
    protected final DocumentTypeRepository documentTypeRepository;

    public DocumentDaoBase(
        DocumentTypeRepository documentTypeRepository,
        DocumentRepository documentRepository
    ) {
        this.documentRepository = documentRepository;
        this.documentTypeRepository = documentTypeRepository;
    }

    /**
     * Sets the reference to <code>documentTypeDao</code>.
     * @param documentTypeDaoIn
     */
    @Autowired
    public void setDocumentTypeDao(@Lazy DocumentTypeDao documentTypeDaoIn)
    {
        this.documentTypeDao = documentTypeDaoIn;
    }
    
    /**
     * Gets the reference to <code>documentTypeDao</code>.
     * @return documentTypeDao
     */
    protected DocumentTypeDao getDocumentTypeDao()
    {
        return this.documentTypeDao;
    }

    /**
     * Gets the reference to <code>documentTypeRepository</code>.
     * @return documentTypeRepository
     */
    protected DocumentTypeRepository getDocumentTypeRepository()
    {
        return this.documentTypeRepository;
    }




        


    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>DocumentDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     * <p>
     * This method will return instances of these types:
     * <ul>
     *   <li>{@link Document} - {@link #TRANSFORM_NONE}</li>
     *   <li>{@link DocumentDTO} - {@link #TRANSFORM_DOCUMENTDTO}</li>
     * </ul>
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link DocumentDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see DocumentDao#transformEntity(int, Document)
     */
    @Override
    public Object transformEntity(final int transform, final Document entity)
    {
        Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_DOCUMENTDTO :
                    target = toDocumentDTO(entity);
                    break;
                case DocumentDao.TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void transformEntities(final int transform, final Collection<?> entities)
    {
        switch (transform)
        {
            case TRANSFORM_DOCUMENTDTO :
                CollectionUtils.transform(entities, this.DOCUMENTDTO_TRANSFORMER);
                break;
            case DocumentDao.TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

    /**
     * @see DocumentDao#toEntities(Collection)
     */
    @Override
    public void toEntities(final Collection<?> results)
    {
        if (results != null)
        {
            CollectionUtils.transform(results, this.ENTITYTRANSFORMER);
        }
    }

    /**
     * This anonymous transformer is designed to transform report query results
     * (which result in an array of entities) to {@link Document}
     * using the Jakarta Commons-Collections Transformation API.
     */
    private Transformer ENTITYTRANSFORMER =
        new Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                Object result = null;
                if (input instanceof Object[])
                {
                    final Object[] rows = (Object[])input;
                    result = toEntity(rows);
                }
                else if (input instanceof Document)
                {
                    result = input;
                }
                return result;
            }
        };

    /**
     * @param row
     * @return Document
     */
    protected Document toEntity(Object[] row)
    {
        Document target = null;
        if (row != null)
        {
            final int numberOfObjects = row.length;
            for (int ctr = 0; ctr < numberOfObjects; ctr++)
            {
                final Object object = row[ctr];
                if (object instanceof Document)
                {
                    target = (Document)object;
                    break;
                }
            }
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({"unchecked"})
    public Collection<DocumentDTO> toDocumentDTOCollection(Collection<Document> entities)
    {
        if (entities == null)
        {
            return null;
        }
        @SuppressWarnings("rawtypes")
        Collection result = new ArrayList(entities);
        CollectionUtils.transform(result, this.DOCUMENTDTO_TRANSFORMER);
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({ "unchecked" })
    public DocumentDTO[] toDocumentDTOArray(Collection<?> entities)
    {
        DocumentDTO[] result = null;
        if (entities != null)
        {
        @SuppressWarnings("rawtypes")
            final Collection collection = new ArrayList(entities);
            this.toDocumentDTOCollection(collection);
            result = (DocumentDTO[]) collection.toArray(new DocumentDTO[collection.size()]);
        }
        return result;
    }

    /**
     * Default implementation for transforming the results of a report query into a value object. This
     * implementation exists for convenience reasons only. It needs only be overridden in the
     * {@link DocumentDaoImpl} class if you intend to use reporting queries.
     * @param row
     * @return toDocumentDTO(this.toEntity(row))
     * @see DocumentDao#toDocumentDTO(Document)
     */
    protected DocumentDTO toDocumentDTO(Object[] row)
    {
        return this.toDocumentDTO(this.toEntity(row));
    }

    /**
     * This anonymous transformer is designed to transform entities or report query results
     * (which result in an array of objects) to {@link DocumentDTO}
     * using the Jakarta Commons-Collections Transformation API.
     */
    private Transformer DOCUMENTDTO_TRANSFORMER =
        new Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                Object result = null;
                if (input instanceof Document)
                {
                    final Document entity = (Document)input;
                    result = toDocumentDTO(entity);
                }
                else if (input instanceof Object[])
                {
                    final Object[] rows = (Object[])input;
                    result = toDocumentDTO(rows);
                }
                return result;
            }
        };

    /**
     * {@inheritDoc}
     */
    @Override
    public void documentDTOToEntityCollection(Collection<?> instances)
    {
        if (instances != null)
        {
            for (final Iterator<?> iterator = instances.iterator(); iterator.hasNext();)
            {
                // - remove an objects that are null or not of the correct instance
                if (!(iterator.next() instanceof DocumentDTO))
                {
                    iterator.remove();
                }
            }
            CollectionUtils.transform(instances, this.DocumentDTOToEntityTransformer);
        }
    }

    private final Transformer DocumentDTOToEntityTransformer =
        new Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                return documentDTOToEntity((DocumentDTO)input);
            }
        };


    /**
     * {@inheritDoc}
     */
    @Override
    public void toDocumentDTO(
        Document source,
        DocumentDTO target)
    {
        // No conversion for target.id (can't convert source.getId():java.lang.Long to java.lang.String)
        target.setId(source.getId());
        target.setCreatedBy(source.getCreatedBy());
        target.setCreatedAt(source.getCreatedAt());
        target.setModifiedBy(source.getModifiedBy());
        target.setModifiedAt(source.getModifiedAt());
        target.setTarget(source.getTarget());
        // No conversion for target.documentType (can't convert source.getDocumentType():bw.co.roguesystems.rfiles.document.type.DocumentType to java.lang.String)
        target.setUrl(source.getUrl());
        target.setSummary(source.getSummary());
        target.setSolrId(source.getSolrId());
        target.setFilename(source.getFilename());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentDTO toDocumentDTO(final Document entity)
    {
        DocumentDTO target = null;
        if (entity != null)
        {
            target =  new DocumentDTO();
            this.toDocumentDTO(entity, target);
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void documentDTOToEntity(
        DocumentDTO source,
        Document target,
        boolean copyIfNull)
    {
        if (copyIfNull || source.getUrl() != null)
        {
            target.setUrl(source.getUrl());
        }
        if (copyIfNull || source.getTarget() != null)
        {
            target.setTarget(source.getTarget());
        }
        if (copyIfNull || source.getSummary() != null)
        {
            target.setSummary(source.getSummary());
        }
        if (copyIfNull || source.getSolrId() != null)
        {
            target.setSolrId(source.getSolrId());
        }
        if (copyIfNull || source.getFilename() != null)
        {
            target.setFilename(source.getFilename());
        }
        if (copyIfNull || source.getCreatedAt() != null)
        {
            target.setCreatedAt(source.getCreatedAt());
        }
        if (copyIfNull || source.getModifiedAt() != null)
        {
            target.setModifiedAt(source.getModifiedAt());
        }
        if (copyIfNull || source.getCreatedBy() != null)
        {
            target.setCreatedBy(source.getCreatedBy());
        }
        if (copyIfNull || source.getModifiedBy() != null)
        {
            target.setModifiedBy(source.getModifiedBy());
        }
    }

    // spring-hibernate-dao-base merge-point
}