// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by HibernateEntityImpl.vsl in andromda-hibernate-cartridge on 07/23/2025 09:12:15+0200.
//
package bw.co.roguesystems.rfiles.document;

/**
 * @see Document
 */
// HibernateEntityImpl.vsl annotations merge-point
public class DocumentImpl
    extends Document
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7779797377213505967L;

// HibernateEntityImpl.vsl merge-point
}