// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringRepository.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.rfiles.document;

import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

public interface DocumentRepository extends 
        JpaRepository<Document, String>,
        JpaSpecificationExecutor<Document> {

    // Generating pageable query method for id
    Page<Document> findByIdNull(Pageable pageable);

    Page<Document> findByIdStartingWithIgnoreCase(String id, Pageable pageable);
    
    Page<Document> findByIdEndingWithIgnoreCase(String id, Pageable pageable);
    
    Page<Document> findByIdContainingIgnoreCase(String id, Pageable pageable);
    
    Page<Document> findByIdLikeIgnoreCase(String id, Pageable pageable);
    
    Page<Document> findByIdNotLikeIgnoreCase(String id, Pageable pageable);
    
    Page<Document> findByIdContaining(String id, Pageable pageable);
    
    // Search by a list of parameters
    List<Document> findByIdNot(String id);
    Page<Document> findByIdNot(String id, Pageable pageable);
    
    List<Document> findByIdIn(List<String> ids);
    Page<Document> findByIdIn(List<String> ids, Pageable pageable);
    
    List<Document> findByIdNotIn(List<String> ids);
    Page<Document> findByIdNotIn(List<String> ids, Pageable pageable);

    // Generating pageable query method for url
    Page<Document> findByUrlNull(Pageable pageable);

    Page<Document> findByUrlStartingWithIgnoreCase(String url, Pageable pageable);
    
    Page<Document> findByUrlEndingWithIgnoreCase(String url, Pageable pageable);
    
    Page<Document> findByUrlContainingIgnoreCase(String url, Pageable pageable);
    
    Page<Document> findByUrlLikeIgnoreCase(String url, Pageable pageable);
    
    Page<Document> findByUrlNotLikeIgnoreCase(String url, Pageable pageable);
    
    Page<Document> findByUrlContaining(String url, Pageable pageable);
    
    // Search by a list of parameters
    List<Document> findByUrlNot(String url);
    Page<Document> findByUrlNot(String url, Pageable pageable);
    
    List<Document> findByUrlIn(List<String> urls);
    Page<Document> findByUrlIn(List<String> urls, Pageable pageable);
    
    List<Document> findByUrlNotIn(List<String> urls);
    Page<Document> findByUrlNotIn(List<String> urls, Pageable pageable);

    // Generating pageable query method for target
    Page<Document> findByTarget(String target, Pageable pageable);

    // Search by a list of parameters
    List<Document> findByTargetNot(String target);
    Page<Document> findByTargetNot(String target, Pageable pageable);
    
    List<Document> findByTargetIn(List<String> targets);
    Page<Document> findByTargetIn(List<String> targets, Pageable pageable);
    
    List<Document> findByTargetNotIn(List<String> targets);
    Page<Document> findByTargetNotIn(List<String> targets, Pageable pageable);

    // Generating pageable query method for targetId
    Page<Document> findByTargetId(String targetId, Pageable pageable);

    Page<Document> findByTargetIdStartingWithIgnoreCase(String targetId, Pageable pageable);
    
    Page<Document> findByTargetIdEndingWithIgnoreCase(String targetId, Pageable pageable);
    
    Page<Document> findByTargetIdContainingIgnoreCase(String targetId, Pageable pageable);
    
    Page<Document> findByTargetIdLikeIgnoreCase(String targetId, Pageable pageable);
    
    Page<Document> findByTargetIdNotLikeIgnoreCase(String targetId, Pageable pageable);
    
    Page<Document> findByTargetIdContaining(String targetId, Pageable pageable);
    
    // Search by a list of parameters
    List<Document> findByTargetIdNot(String targetId);
    Page<Document> findByTargetIdNot(String targetId, Pageable pageable);
    
    List<Document> findByTargetIdIn(List<String> targetIds);
    Page<Document> findByTargetIdIn(List<String> targetIds, Pageable pageable);
    
    List<Document> findByTargetIdNotIn(List<String> targetIds);
    Page<Document> findByTargetIdNotIn(List<String> targetIds, Pageable pageable);

    // Generating pageable query method for summary
    Page<Document> findBySummaryNull(Pageable pageable);

    Page<Document> findBySummaryStartingWithIgnoreCase(String summary, Pageable pageable);
    
    Page<Document> findBySummaryEndingWithIgnoreCase(String summary, Pageable pageable);
    
    Page<Document> findBySummaryContainingIgnoreCase(String summary, Pageable pageable);
    
    Page<Document> findBySummaryLikeIgnoreCase(String summary, Pageable pageable);
    
    Page<Document> findBySummaryNotLikeIgnoreCase(String summary, Pageable pageable);
    
    Page<Document> findBySummaryContaining(String summary, Pageable pageable);
    
    // Search by a list of parameters
    List<Document> findBySummaryNot(String summary);
    Page<Document> findBySummaryNot(String summary, Pageable pageable);
    
    List<Document> findBySummaryIn(List<String> summarys);
    Page<Document> findBySummaryIn(List<String> summarys, Pageable pageable);
    
    List<Document> findBySummaryNotIn(List<String> summarys);
    Page<Document> findBySummaryNotIn(List<String> summarys, Pageable pageable);

    // Generating pageable query method for solrId
    Document findBySolrId(String solrId);

    Page<Document> findBySolrIdNull(Pageable pageable);

    Page<Document> findBySolrIdStartingWithIgnoreCase(String solrId, Pageable pageable);
    
    Page<Document> findBySolrIdEndingWithIgnoreCase(String solrId, Pageable pageable);
    
    Page<Document> findBySolrIdContainingIgnoreCase(String solrId, Pageable pageable);
    
    Page<Document> findBySolrIdLikeIgnoreCase(String solrId, Pageable pageable);
    
    Page<Document> findBySolrIdNotLikeIgnoreCase(String solrId, Pageable pageable);
    
    Page<Document> findBySolrIdContaining(String solrId, Pageable pageable);
    
    // Search by a list of parameters
    List<Document> findBySolrIdNot(String solrId);
    Page<Document> findBySolrIdNot(String solrId, Pageable pageable);
    
    List<Document> findBySolrIdIn(List<String> solrIds);
    Page<Document> findBySolrIdIn(List<String> solrIds, Pageable pageable);
    
    List<Document> findBySolrIdNotIn(List<String> solrIds);
    Page<Document> findBySolrIdNotIn(List<String> solrIds, Pageable pageable);

    // Generating pageable query method for filename
    Page<Document> findByFilename(String filename, Pageable pageable);

    Page<Document> findByFilenameStartingWithIgnoreCase(String filename, Pageable pageable);
    
    Page<Document> findByFilenameEndingWithIgnoreCase(String filename, Pageable pageable);
    
    Page<Document> findByFilenameContainingIgnoreCase(String filename, Pageable pageable);
    
    Page<Document> findByFilenameLikeIgnoreCase(String filename, Pageable pageable);
    
    Page<Document> findByFilenameNotLikeIgnoreCase(String filename, Pageable pageable);
    
    Page<Document> findByFilenameContaining(String filename, Pageable pageable);
    
    // Search by a list of parameters
    List<Document> findByFilenameNot(String filename);
    Page<Document> findByFilenameNot(String filename, Pageable pageable);
    
    List<Document> findByFilenameIn(List<String> filenames);
    Page<Document> findByFilenameIn(List<String> filenames, Pageable pageable);
    
    List<Document> findByFilenameNotIn(List<String> filenames);
    Page<Document> findByFilenameNotIn(List<String> filenames, Pageable pageable);

}