// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringServiceBase.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
/**
 * TEMPLATE:    SpringServiceBase.vsl in andromda-spring cartridge
 * MODEL CLASS: AndroMDAModel::backend::bw.co.roguesystems.rfiles::document::DocumentService
 * STEREOTYPE:  Service
 */
package bw.co.roguesystems.rfiles.document;

import java.io.File;
import java.security.Principal;
import java.util.Collection;
import java.util.Locale;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Page;

/**
 * <p>
 * Spring Service base class for <code>DocumentService</code>,
 * provides access to all services and entities referenced by this service.
 * </p>
 *
 * @see DocumentService
 */
public abstract class DocumentServiceBase
    implements DocumentService
{
    protected Logger logger = LoggerFactory.getLogger(DocumentService.class);
    protected final DocumentDao documentDao;
    protected final DocumentRepository documentRepository;
    protected final MessageSource messageSource;

    public DocumentServiceBase(
        DocumentDao documentDao,
        DocumentRepository documentRepository,
        MessageSource messageSource
    ) {
        this.documentDao = documentDao;
        this.documentRepository = documentRepository;
        this.messageSource = messageSource;
    }

	/**
     * Gets the reference to <code>document</code>'s DAO.
     * @return documentDao
     */
    protected DocumentDao getDocumentDao()
    {
        return this.documentDao;
    }

    /**
     * Gets the reference to <code>document</code>'s repository.
     * @return documentRepository
     */
    public DocumentRepository getDocumentRepository() {
        return documentRepository;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentDTO findById(final String id)
    {
        if (id == null || id.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.findById(String id) - 'id' can not be null or empty");
        }
        try
        {
            return this.handleFindById(id);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.findById(String id)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #findById(String)}
     * @param id String TODO: Model Documentation for DocumentService.findById(id)
     * @return DocumentDTO
     * @throws Exception
     */
    protected abstract DocumentDTO handleFindById(String id)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentDTO save(final DocumentDTO document)
    {
        if (document == null)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.save(DocumentDTO document) - 'document' can not be null");
        }
        if (document.getFilename() == null || document.getFilename().trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.save(DocumentDTO document) - 'document.filename' can not be null or empty");
        }
        try
        {
            return this.handleSave(document);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.save(DocumentDTO document)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #save(DocumentDTO)}
     * @param document DocumentDTO TODO: Model Documentation for DocumentService.save(document)
     * @return DocumentDTO
     * @throws Exception
     */
    protected abstract DocumentDTO handleSave(DocumentDTO document)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean remove(final String id)
    {
        if (id == null || id.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.remove(String id) - 'id' can not be null or empty");
        }
        try
        {
            return this.handleRemove(id);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.remove(String id)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #remove(String)}
     * @param id String TODO: Model Documentation for DocumentService.remove(id)
     * @return boolean
     * @throws Exception
     */
    protected abstract boolean handleRemove(String id)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Collection<DocumentDTO> getAll()
    {
        try
        {
            return this.handleGetAll();
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.getAll()' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #getAll()}
     * @return Collection<DocumentDTO>
     * @throws Exception
     */
    protected abstract Collection<DocumentDTO> handleGetAll()
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Collection<DocumentDTO> search(final String criteria)
    {
        if (criteria == null || criteria.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.search(String criteria) - 'criteria' can not be null or empty");
        }
        try
        {
            return this.handleSearch(criteria);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.search(String criteria)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #search(String)}
     * @param criteria String TODO: Model Documentation for DocumentService.search(criteria)
     * @return Collection<DocumentDTO>
     * @throws Exception
     */
    protected abstract Collection<DocumentDTO> handleSearch(String criteria)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Page<DocumentDTO> getAll(final Integer pageNumber, final Integer pageSize)
    {
        try
        {
            return this.handleGetAll(pageNumber, pageSize);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.getAll(Integer pageNumber, Integer pageSize)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #getAll(Integer, Integer)}
     * @param pageNumber Integer TODO: Model Documentation for DocumentService.getAll(pageNumber)
     * @param pageSize Integer TODO: Model Documentation for DocumentService.getAll(pageSize)
     * @return Page<DocumentDTO>
     * @throws Exception
     */
    protected abstract Page<DocumentDTO> handleGetAll(Integer pageNumber, Integer pageSize)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Collection<DocumentDTO> findByDocumentType(final String documentTypeId)
    {
        if (documentTypeId == null || documentTypeId.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.findByDocumentType(String documentTypeId) - 'documentTypeId' can not be null or empty");
        }
        try
        {
            return this.handleFindByDocumentType(documentTypeId);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.findByDocumentType(String documentTypeId)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #findByDocumentType(String)}
     * @param documentTypeId String TODO: Model Documentation for
DocumentService.findByDocumentType(documentTypeId)
     * @return Collection<DocumentDTO>
     * @throws Exception
     */
    protected abstract Collection<DocumentDTO> handleFindByDocumentType(String documentTypeId)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentDTO upload(final String target, final String targetId, final String documentTypeId, final File file, final String user)
    {
        if (target == null)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.upload(String target, String targetId, String documentTypeId, File file, String user) - 'target' can not be null");
        }
        if (targetId == null || targetId.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.upload(String target, String targetId, String documentTypeId, File file, String user) - 'targetId' can not be null or empty");
        }
        if (documentTypeId == null || documentTypeId.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.upload(String target, String targetId, String documentTypeId, File file, String user) - 'documentTypeId' can not be null or empty");
        }
        if (file == null)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.upload(String target, String targetId, String documentTypeId, File file, String user) - 'file' can not be null");
        }
        if (user == null || user.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.upload(String target, String targetId, String documentTypeId, File file, String user) - 'user' can not be null or empty");
        }
        try
        {
            return this.handleUpload(target, targetId, documentTypeId, file, user);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.upload(String target, String targetId, String documentTypeId, File file, String user)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #upload(String, String, String, File, String)}
     * @param target String TODO: Model Documentation for DocumentService.upload(target)
     * @param targetId String TODO: Model Documentation for DocumentService.upload(targetId)
     * @param documentTypeId String TODO: Model Documentation for
DocumentService.upload(documentTypeId)
     * @param file File TODO: Model Documentation for DocumentService.upload(file)
     * @param user String TODO: Model Documentation for DocumentService.upload(user)
     * @return DocumentDTO
     * @throws Exception
     */
    protected abstract DocumentDTO handleUpload(String target, String targetId, String documentTypeId, File file, String user)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Collection<DocumentDTO> findByTarget(final String target, final String targetId)
    {
        if (target == null)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.findByTarget(String target, String targetId) - 'target' can not be null");
        }
        if (targetId == null || targetId.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.findByTarget(String target, String targetId) - 'targetId' can not be null or empty");
        }
        try
        {
            return this.handleFindByTarget(target, targetId);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.findByTarget(String target, String targetId)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #findByTarget(String, String)}
     * @param target String TODO: Model Documentation for DocumentService.findByTarget(target)
     * @param targetId String TODO: Model Documentation for
DocumentService.findByTarget(targetId)
     * @return Collection<DocumentDTO>
     * @throws Exception
     */
    protected abstract Collection<DocumentDTO> handleFindByTarget(String target, String targetId)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentDTO updateFile(final String id, final String url, final String user)
    {
        if (id == null || id.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.updateFile(String id, String url, String user) - 'id' can not be null or empty");
        }
        if (url == null || url.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.updateFile(String id, String url, String user) - 'url' can not be null or empty");
        }
        if (user == null || user.trim().length() == 0)
        {
            throw new IllegalArgumentException(
                "bw.co.roguesystems.rfiles.document.DocumentService.updateFile(String id, String url, String user) - 'user' can not be null or empty");
        }
        try
        {
            return this.handleUpdateFile(id, url, user);
        }
        catch (Throwable th)
        {
            throw new DocumentServiceException(
                "Error performing 'DocumentService.updateFile(String id, String url, String user)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #updateFile(String, String, String)}
     * @param id String TODO: Model Documentation for DocumentService.updateFile(id)
     * @param url String TODO: Model Documentation for DocumentService.updateFile(url)
     * @param user String TODO: Model Documentation for DocumentService.updateFile(user)
     * @return DocumentDTO
     * @throws Exception
     */
    protected abstract DocumentDTO handleUpdateFile(String id, String url, String user)
        throws Exception;

    /**
     * Gets the message source available to this service.
     * @return MessageSource
     */
    protected MessageSource getMessages()
    {
        return messageSource;
    }

    /**
     * Gets the message having the given <code>key</code> in the underlying message bundle.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @return String
     */
    protected String getMessage(final String key)
    {
        return this.getMessages().getMessage(key, null, null);
    }

    /**
     * Gets the message having the given <code>key</code> and <code>arguments</code> in the
     * underlying message bundle.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @param arguments any arguments to substitute when resolving the message.
     * @return String
     */
    protected String getMessage(final String key, final Object[] arguments)
    {
        return this.getMessages().getMessage(key, arguments, null);
    }

    /**
     * Gets the message having the given <code>key</code> using the given <code>arguments</code>
     * for the given <code>locale</code>.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @param arguments any arguments to substitute when resolving the message.
     * @param locale the locale of the messages to retrieve.
     * @return String
     */
    protected String getMessage(
        final String key, final Object[] arguments,
        final Locale locale)
    {
        return this.getMessages().getMessage(key, arguments, locale);
    }


// spring-service-base merge-point
}