// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge on 07/23/2025 09:12:15+0200.
//
package bw.co.roguesystems.rfiles.document;

import bw.co.roguesystems.rfiles.Auditable;
import bw.co.roguesystems.rfiles.document.type.DocumentType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * TODO: Model Documentation for Document
 */
@Entity
@Table(name = "DOCUMENT")
// Uncomment to enable caching for Document
// @org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.read-write)
@NamedQuery(name = "Document.findAll", query = "SELECT d FROM Document AS d")
@Data
// HibernateEntity.vsl annotations merge-point
public class Document
    extends Auditable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7779797377213505967L;

    // Generate 7 attributes
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)

    @Column(name = "ID", unique = false, nullable = true, insertable = true, updatable = true)
    private String id;


    @Column(name = "URL", unique = false, nullable = true, insertable = true, updatable = true)
    private String url;


    @Column(name = "TARGET", unique = false, nullable = false, insertable = true, updatable = true)
    private String target;


    @Column(name = "TARGET_ID", unique = false, nullable = false, insertable = true, updatable = true)
    private String targetId;


    @Column(name = "SUMMARY", unique = false, nullable = true, insertable = true, updatable = true, columnDefinition = "TEXT")
    private String summary;


    @Column(name = "SOLR_ID", unique = false, nullable = true, insertable = true, updatable = true)
    private String solrId;


    @Column(name = "FILENAME", unique = false, nullable = false, insertable = true, updatable = true)
    private String filename;

    // Generate 1 associations
    @ManyToOne(optional = false,  fetch = FetchType.LAZY)
    @JoinColumn(name = "DOCUMENT_TYPE_FK")
    private DocumentType documentType;

    // HibernateEntity.vsl equals and hashCode merge-point
    /**
     * Returns <code>true</code> if the argument is an Document instance and all identifiers for this entity
     * equal the identifiers of the argument entity. The <code>equals</code> method of the parent entity
     * will also need to return <code>true</code>. Returns <code>false</code> otherwise.
     *
     * @see Auditable#equals(Object)
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Document))
        {
            return false;
        }
        final Document that = (Document)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers and the hash code of the parent entity.
     *
     * @see Auditable#hashCode()
     */
    @Override
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link Document}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link Document}.
         * @return new Document()
         */
        public static Document newInstance()
        {
            return new Document();
        }

        /**
         * Constructs a new instance of {@link Document}, taking all required and/or
         * read-only properties as arguments, except for identifiers.
         * @param createdAt LocalDateTime
         * @param createdBy String
         * @param target String
         * @param targetId String
         * @param filename String
         * @param documentType DocumentType
         * @return newInstance
         */
        public static Document newInstance(LocalDateTime createdAt, String createdBy, String target, String targetId, String filename, DocumentType documentType)
        {
            final Document entity = new Document();
            entity.setCreatedAt(createdAt);
            entity.setCreatedBy(createdBy);
            entity.setTarget(target);
            entity.setTargetId(targetId);
            entity.setFilename(filename);
            entity.setDocumentType(documentType);
            return entity;
        }

        /**
         * Constructs a new instance of {@link Document}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param createdAt LocalDateTime
         * @param modifiedAt LocalDateTime
         * @param createdBy String
         * @param modifiedBy String
         * @param url String
         * @param target String
         * @param targetId String
         * @param summary String
         * @param solrId String
         * @param filename String
         * @param documentType DocumentType
         * @return newInstance Document
         */
        public static Document newInstance(LocalDateTime createdAt, LocalDateTime modifiedAt, String createdBy, String modifiedBy, String url, String target, String targetId, String summary, String solrId, String filename, DocumentType documentType)
        {
            final Document entity = new Document();
            entity.setCreatedAt(createdAt);
            entity.setModifiedAt(modifiedAt);
            entity.setCreatedBy(createdBy);
            entity.setModifiedBy(modifiedBy);
            entity.setUrl(url);
            entity.setTarget(target);
            entity.setTargetId(targetId);
            entity.setSummary(summary);
            entity.setSolrId(solrId);
            entity.setFilename(filename);
            entity.setDocumentType(documentType);
            return entity;
        }
    }

    /**
     * @param other
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the specified object.
     * @see Comparable#compareTo
     */
    public int compareTo(Document other)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(other.getId());
        }
        else
        {
            if (this.getUrl() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getUrl().compareTo(other.getUrl()));
            }
            if (this.getTarget() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getTarget().compareTo(other.getTarget()));
            }
            if (this.getTargetId() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getTargetId().compareTo(other.getTargetId()));
            }
            if (this.getSummary() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getSummary().compareTo(other.getSummary()));
            }
            if (this.getSolrId() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getSolrId().compareTo(other.getSolrId()));
            }
            if (this.getFilename() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getFilename().compareTo(other.getFilename()));
            }
        }
        return cmp;
    }

    /**
     * Returns a String representation of the object
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     * @see Object#toString
     */
    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("Document(");
        sb.append(super.toString());
        sb.append(" id=").append(getId());
        sb.append(" url=").append(getUrl());
        sb.append(" target=").append(getTarget());
        sb.append(" targetId=").append(getTargetId());
        sb.append(" summary=").append(getSummary());
        sb.append(" solrId=").append(getSolrId());
        sb.append(" filename=").append(getFilename());
        sb.append(" createdAt=").append(getCreatedAt());
        sb.append(" modifiedAt=").append(getModifiedAt());
        sb.append(" createdBy=").append(getCreatedBy());
        sb.append(" modifiedBy=").append(getModifiedBy());
        sb.append(")");
        return sb.toString();
    }
// HibernateEntity.vsl merge-point
}