// license-header java merge-point
//
/**
 * @author Generated by Service.vsl in andromda-java-cartridge on 07/23/2025 09:12:17+0200 Do not modify by hand!
 *
 * TEMPLATE:     Service.vsl in andromda-java-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.roguesystems.rfiles::document::DocumentService
 * STEREOTYPE:   Service
 */
package bw.co.roguesystems.rfiles.document;

import java.io.File;
import java.util.Collection;
import org.springframework.data.domain.Page;

/**
 * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService
 */
public interface DocumentService
{
    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.findById
     * @param id TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.findById(id)
     * @return DocumentDTO
     */
    public DocumentDTO findById(String id) ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.save
     * @param document TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.save(document)
     * @return DocumentDTO
     */
    public DocumentDTO save(DocumentDTO document) ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.remove
     * @param id TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.remove(id)
     * @return boolean
     */
    public boolean remove(String id) ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.getAll
     * @return Collection<DocumentDTO>
     */
    public Collection<DocumentDTO> getAll() ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.search
     * @param criteria TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.search(criteria)
     * @return Collection<DocumentDTO>
     */
    public Collection<DocumentDTO> search(String criteria) ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.getAll
     * @param pageNumber TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.getAll(pageNumber)
     * @param pageSize TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.getAll(pageSize)
     * @return Page<DocumentDTO>
     */
    public Page<DocumentDTO> getAll(Integer pageNumber, Integer pageSize) ;

    /**
     * TODO: Model Documentation for
     * bw.co.roguesystems.rfiles.document.DocumentService.findByDocumentType
     * @param documentTypeId TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.DocumentService.findByDocumentType(documentTypeId)
     * @return Collection<DocumentDTO>
     */
    public Collection<DocumentDTO> findByDocumentType(String documentTypeId) ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.upload
     * @param target TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.upload(target)
     * @param targetId TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.upload(targetId)
     * @param documentTypeId TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.DocumentService.upload(documentTypeId)
     * @param file TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.upload(file)
     * @param user TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.upload(user)
     * @return DocumentDTO
     */
    public DocumentDTO upload(String target, String targetId, String documentTypeId, File file, String user) ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.findByTarget
     * @param target TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.findByTarget(target)
     * @param targetId TODO: Model Documentation for
bw.co.roguesystems.rfiles.document.DocumentService.findByTarget(targetId)
     * @return Collection<DocumentDTO>
     */
    public Collection<DocumentDTO> findByTarget(String target, String targetId) ;

    /**
     * TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.updateFile
     * @param id TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.updateFile(id)
     * @param url TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.updateFile(url)
     * @param user TODO: Model Documentation for bw.co.roguesystems.rfiles.document.DocumentService.updateFile(user)
     * @return DocumentDTO
     */
    public DocumentDTO updateFile(String id, String url, String user) ;

}