// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.rfiles.document;

import bw.co.roguesystems.rfiles.document.type.DocumentType;
import bw.co.roguesystems.rfiles.document.type.DocumentTypeRepository;
import jakarta.persistence.EntityNotFoundException;

import java.util.HashMap;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Repository;

/**
 * @see Document
 */
@Repository("documentDao")
public class DocumentDaoImpl
        extends DocumentDaoBase {


    public DocumentDaoImpl(
            DocumentTypeRepository documentTypeRepository,
            DocumentRepository documentRepository) {

        super(
                documentTypeRepository,
                documentRepository);

    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toDocumentDTO(
            Document source,
            DocumentDTO target) {
        // TODO verify behavior of toDocumentDTO
        super.toDocumentDTO(source, target);
        // WARNING! No conversion for target.documentType (can't convert
        // source.getDocumentType():bw.co.roguesystems.rfiles.document.type.DocumentType
        // to java.lang.String
        if (source.getDocumentType() != null) {
            target.setDocumentTypeId(source.getDocumentType().getId());
            target.setDocumentType(source.getDocumentType().getName());
            target.setDocumentTypeCode(source.getDocumentType().getCode());
        }

        // if (StringUtils.isNotBlank(source.getTargetId())) {

        //     switch (source.getTarget()) {
        //         case REGULATOR:
        //             Regulator regulator = this.regulatorRepository.findById(source.getTargetId())
        //                     .orElseThrow(() -> new EntityNotFoundException(
        //                             "Regulator not found for id: " + source.getTargetId()));

        //             target.setOwner(regulator.getName());
        //             target.setOwnerId(regulator.getId());
        //             break;
        //         case SERVICE:
        //         case REGULATED_OPERATION:
        //             RegulatedOperation op = this.regulatedOperationRepository.findById(source.getTargetId())
        //                     .orElseThrow(() -> new EntityNotFoundException(
        //                             "Regulated Operation not found for id: " + source.getTargetId()));

        //             target.setOwner(op.getName());
        //             target.setOwnerId(op.getId());
        //             break;
        //         case PROCESS:
        //             Process process = this.processRepository.findById(source.getTargetId())
        //                     .orElseThrow(() -> new EntityNotFoundException(
        //                             "Process not found for id: " + source.getTargetId()));

        //             target.setOwner(process.getName());
        //             target.setOwnerId(process.getId());
        //             break;

        //         case REGULATED_OPERATION_PROCESS:
        //             bw.co.roguesystems.rfiles.operation.process.RegulatedOperationProcess regulatedOperationProcess =
        //                     this.regulatedOperationProcessRepository.findById(source.getTargetId())
        //                             .orElseThrow(() -> new EntityNotFoundException(
        //                                     "Regulated Operation Process not found for id: " + source.getTargetId()));
        //             target.setOwner(regulatedOperationProcess.getDescription());
        //             target.setOwnerId(regulatedOperationProcess.getId());
        //             break;
        //         default:
        //             break;
        //     }
        // }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DocumentDTO toDocumentDTO(final Document entity) {
        // TODO verify behavior of toDocumentDTO
        return super.toDocumentDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value
     * object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Document loadDocumentFromDocumentDTO(DocumentDTO documentDTO) {
        if (documentDTO.getId() == null) {
            return Document.Factory.newInstance();
        } else {
            return this.documentRepository.findById(documentDTO.getId())
                    .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + documentDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public Document documentDTOToEntity(DocumentDTO documentDTO) {
        // TODO verify behavior of documentDTOToEntity
        Document entity = this.loadDocumentFromDocumentDTO(documentDTO);
        this.documentDTOToEntity(documentDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void documentDTOToEntity(
            DocumentDTO source,
            Document target,
            boolean copyIfNull) {
        // TODO verify behavior of documentDTOToEntity
        super.documentDTOToEntity(source, target, copyIfNull);

        if (StringUtils.isNotBlank(source.getOwnerId())) {
            target.setTargetId(source.getOwnerId());
        }

        if (StringUtils.isNotBlank(source.getDocumentTypeId())) {

            DocumentType documentType = this.documentTypeRepository.findById(source.getDocumentTypeId()).orElseThrow(
                    () -> new IllegalArgumentException("Document type not found"));
            target.setDocumentType(documentType);
        }
    }
}